### ISSUE TITLE
Publish per-commit dev builds

### ISSUE THREAD

**Issue by tonsky** [JetBrains/skiko#113]
So that after a PR is merged you don’t have to wait for release

**Comment by olonho** [comment]
Snapshot builds already run on every commit.

**Comment by tonsky** [comment]
Can you add the info on how to use them to the README?

**Comment by olonho** [comment]
Updated README.md.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-113">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
