### ISSUE TITLE
Any plans to support JavaFX?

### ISSUE THREAD

**Issue by pusolito** [JetBrains/skiko#119]
Swing is fairly outdated and limited. Are there plans to provide SkiaLayer/Window etc. based on JavaFX components?

**Comment by olonho** [comment]
No immediate plans, but contributions will be considered.

**Comment by calebkiage** [comment]
@olonho, can the build system have multiple jvm targets?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-119">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
