### ISSUE TITLE
SkiaPanels Stutter on Window Resize (Mac)

### ISSUE THREAD

**Issue by pusolito** [JetBrains/skiko#120]
Vertical resizing of the window causes the SkiaPanels to jump up and down. This doesn't happen on horizontal resize.

https://user-images.githubusercontent.com/9815928/121550034-38949780-c9c3-11eb-824c-4e127c0ff22c.mov

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-120">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
