### ISSUE TITLE
How expensive are SkiaLayers?

### ISSUE THREAD

**Issue by pusolito** [JetBrains/skiko#122]
Would perf suffer if one is used for every UI component in an app?

**Comment by olonho** [comment]
It is separate native window, AWT Canvas and Skia hardware rendering context. Not sure if using it for every component is good idea, it's pretty heavyweight.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-122">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
