### ISSUE TITLE
 UI on HiDPI on Linux is too blurry

### ISSUE THREAD

**Issue by zeburek** [JetBrains/skiko#124]
# Env
Fedora 34 with Gnome 40
Huawei Matebook X Pro 3000x2000 with 175% scale

Tried running example skiko app on HiDPI screen - and quality of displayed elements is lower then the quality of original Gnome applications.

# Example Preview (please zoom to original size to see difference)
![image](https://user-images.githubusercontent.com/20853475/122734274-9a3be800-d286-11eb-99d5-dc4f7073d576.png)

**Comment by zeburek** [comment]
![image](https://user-images.githubusercontent.com/20853475/122735015-4a115580-d287-11eb-8059-04f230eed785.png)
Compare with the light background

**Comment by Rsedaikin** [comment]
Please try again with the latest commit (Fix linux dpi).

**Comment by zeburek** [comment]
It looks OK with 100% screen scale, but does not for any other variant, e.g. for 200%
![image](https://user-images.githubusercontent.com/20853475/123398958-c029fb00-d5ac-11eb-9fa3-38f56d609f32.png)

**Comment by Rsedaikin** [comment]
Try the https://github.com/JetBrains/skiko/tree/dpi-debug branch, rebuild `skiko`, run the example and send the console output.
It will look like this:
```
Trying OPENGL rendering...
GraphicsApi: OPENGL
OS: Linux, 5.12.0-051200-lowlatency, x64
System OS DPI scale: 2.0
Java: AdoptOpenJDK 11.0.11
Java location: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
Vendor: nouveau
Model: NV164
Total VRAM: 31 MB

[799247] FPS 54 (6-121)
...
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-124">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
