### ISSUE TITLE
Reorganized folders in Skija

### ISSUE THREAD

**Issue by tonsky** [JetBrains/skiko#125]
Hi!

I’ve reorganized source folders in Skija. Jars will continue to work as they used to, but since you don’t depend on jars, you might need some adjustments.

The change is all summarized in this tiny 323 changed files with 859 additions and 646 deletions commit: https://github.com/JetBrains/skija/commit/37d3d6ec1dabf0528f4fcc2bcbe16f4c9b3f196b

- native/src → platform/cc
- shared/src/main/java/org/jetbrains/skija → shared/java
- shared/src/test/java/org/jetbrains/skija → tests/java

**Comment by olonho** [comment]
Fixed with https://github.com/JetBrains/skiko/pull/127

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-125">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
