### ISSUE TITLE
Will there be support for JS in Skiko?

### ISSUE THREAD

**Issue by adorokhine** [JetBrains/skiko#138]
Hello, I see that Skiko targets Kotlin MPP but it's unclear what targets are supported. Is JS going to be a supported target? I see that Skia has released CanvasKit which seems to be a webassembly port of the library, so it seems like this should be possible to support.

**Comment by olonho** [comment]
We're considering that, but no definite plans yet.

**Comment by olonho** [comment]
We're working on that right now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-138">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
