### ISSUE TITLE
Can't access `Paint.setColor` from Java

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#206]
There is a conflict between 
https://github.com/JetBrains/skiko/blob/7d0514fd2093537e4d4d90ed33741cdba969a64f/skiko/src/commonMain/kotlin/org/jetbrains/skia/Paint.kt#L192
and
https://github.com/JetBrains/skiko/blob/7d0514fd2093537e4d4d90ed33741cdba969a64f/skiko/src/commonMain/kotlin/org/jetbrains/skia/Paint.kt#L211
that doesn't allow Java access to `color`.

**Comment by olonho** [comment]
Fixed by https://github.com/JetBrains/skiko/pull/213

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-206">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
