### ISSUE TITLE
Typo: The target should be "${targetOs}-${targetArch}"

### ISSUE THREAD

**Issue by drakeet** [JetBrains/skiko#22]
After running `./gradlew publishToMavenLocal`, _skiko-jvm-runtime-macos-x64_ will be generated, but gradle is looking for _skiko-jvm-runtime-macos_x64_:

![image](https://user-images.githubusercontent.com/5214214/99652584-f5a8bc00-2a92-11eb-9656-03acc59acbc1.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-22">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
