### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by RedStoneCats101** [JetBrains/skiko#231]
Cannot build SkiaNativeSample

Error 
Could not resolve org.jetbrains.skiko:skiko:0.0.0-SNAPSHOT. (0.4.16 also dose not work)
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by olonho** [comment]
Skiko native targets are not yet officially supported, to try it do `./gradlew  -Pskiko.native.enabled=true publishToMavenLocal` in `skiko` directory first.

**Comment by RedStoneCats101** [comment]
Ok thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-231">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
