### ISSUE TITLE
canvas.drawString cannot draw emoji

### ISSUE THREAD

**Issue by drakeet** [JetBrains/skiko#26]
Add an emoji to the text in `SkijaInjectSample.AppKt#displayScene`:

```
val text = "${state.text} 😄 ${state.frame++}!"
canvas.drawString(text, xpos.toFloat(), ypos.toFloat(), renderer.font, renderer.paint)
```

Result:
(The emoji is displayed as `[/]`)
![image](https://user-images.githubusercontent.com/5214214/100530113-e52dd980-3228-11eb-85c6-b4a99dbdee55.png)

**Comment by olonho** [comment]
This is just result of the fact that we explicitly select font without emojis when drawing the text.  Add emoji into paragraph, i.e.
```
    val fontCollection = FontCollection()
            .setDefaultFontManager(FontMgr.getDefault())
    val style = ParagraphStyle()
    val paragraph = ParagraphBuilder(style, fontCollection)
            .pushStyle(TextStyle().setColor(0xFF000000.toInt()))
            .addText("Text \uD83E\uDD29")
            .popStyle()
            .build()
    paragraph.layout(Float.POSITIVE_INFINITY)
    paragraph.paint(canvas, 0f, 0f)
```
and it will be rendered as expected.

**Comment by drakeet** [comment]
@olonho Thank you for your answer! But is it better if `drawString` can also support emoji? Because when we call to draw a string, it is difficult for us to predict whether there is emoji in it. If it cannot draw emoji, the usability is actually very poor.
