### ISSUE TITLE
Remove "NO DC" on Windows when we use OpenGL renderer (or transparent window)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#270]
Skiko 0.5.1

Windows 11, NVIDIA videocard

Force OpenGL:
```
 System.setProperty("skiko.renderApi", "OPENGL")
```

Run skiko application.

See "NO-DC" in the corner:
![image](https://user-images.githubusercontent.com/5963351/137313996-490e1fee-4d6a-4717-b888-363d7f051d63.png)

**Comment by olonho** [comment]
https://github.com/godotengine/godot-docs/pull/4753

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-270">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
