### ISSUE TITLE
Support Wayland display servers natively 

### ISSUE THREAD

**Issue by kevincianfarini** [JetBrains/skiko#28]
I noticed in [`drawlayer.cc`](https://github.com/JetBrains/skiko/blob/master/skiko/src/jvmMain/cpp/linux/drawlayer.cc#L5) that explicit calls are made into X11. Compose apps (for example) can be verified that they're using the XWayland compatibility layer using the program `xeyes`. 

https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a

Is there any roadmap for supporting Wayland display servers natively? Linux distributions are generally moving towards Wayland and only maintaining backwards compatibility with XWayland. My distro of choice, Fedora, has been shipping a functioning Wayland session since 2016. At some point in time, X11 will be deprecated.

**Comment by olonho** [comment]
It's mostly related to JAWT support for Wayland, we just need to interop with the way how AWT renders, so unlikely much could be done here.

**Comment by JakeWharton** [comment]
With IntelliJ moving JBR/OpenJDK to run directly on Wayland rather than through XWayland, can this be reconsidered?

https://blog.jetbrains.com/platform/2023/08/wayland-support/

**Comment by JakeWharton** [comment]
Because it predates GitHub [adding different close states](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-28">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
