### ISSUE TITLE
Crash on resize on Windows 11 with Direct3D

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#282]
[hs_err_pid5740.log](https://github.com/JetBrains/skiko/files/7373403/hs_err_pid5740.log)
videocard: Nvidia GTX1660
os: Windows 10

**Comment by nskvortsov** [comment]
Windows 11 to be exact

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-282">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
