### ISSUE TITLE
Using public api for disabling anti aliasing results in crash

### ISSUE THREAD

**Issue by jakobkmar** [JetBrains/skiko#304]
I tried to create a `Canvas` which disables anti aliasing for some drawcalls using `PaintFilterCanvas`.

But the following code results in a crash:

```kt
val canvasWithoutAntialias = object : PaintFilterCanvas(canvas, true) {
    override fun onFilter(paint: Paint): Boolean {
        paint.isAntiAlias = false
        return true
    }
}
```

**Comment by jakobkmar** [comment]
Tested again in a more recent version and now it seems to fail silently, as in no crash anymore, but anti aliasing is still active.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-304">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
