### ISSUE TITLE
libskiko-macos-x64.dylib is not code signed

### ISSUE THREAD

**Issue by alexjpwalker** [JetBrains/skiko#314]
The JAR distribution of `skiko-jvm-runtime-macos-x64`, version 0.5.6 (hosted at https://mvnrepository.com/artifact/org.jetbrains.skiko/skiko-jvm-runtime-macos-x64/0.5.6) contains a `.dylib` file, `libskiko-macos-x64.dylib`, which is not code signed. This causes installation of Mac apps to fail that depend on Skiko.

**Additional Information**
The equivalent `.dylib` file in version 0.3.9 is code signed correctly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-314">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
