### ISSUE TITLE
Skiko should try using System.loadLibrary first

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/skiko#321]
Currently Skiko is very keen on being told the absolute path to its own library. With some packagings this just isn't necessary. `System.loadLibrary` will work fine. Skiko should try that first and only try to use an absolute path if the system property is actually set.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-321">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
