### ISSUE TITLE
Build fails due to missing a lot of cpp headers

### ISSUE THREAD

**Issue by CeH9** [JetBrains/skiko#37]
Following guide in readme but got this:
![image](https://user-images.githubusercontent.com/7687412/104065267-2215c480-5208-11eb-90f2-c112be47e02b.png)

**Comment by CeH9** [comment]
Nevermind, it was my fault

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-37">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
