### ISSUE TITLE
Black area on iphone 13 (iOS 15, Xcode 13) 

### ISSUE THREAD

**Issue by b95505017** [JetBrains/skiko#398]
![截圖 2021-11-19 上午2 19 48](https://user-images.githubusercontent.com/320815/142474076-10156ef2-569d-4cff-acf9-790ee848d95e.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-398">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
