### ISSUE TITLE
Can't get SystemTheme in Linux

### ISSUE THREAD

**Issue by purofle** [JetBrains/skiko#403]
My code:
```kotlin
fun main() {
  println(org.jetbrains.skiko.currentSystemTheme)
}
```
But it returns "UNKNOWN".

**Comment by DevSrSouza** [comment]
Linux does not have a Cross desktop system dark theme.

https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/

https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/

**Comment by olonho** [comment]
Yes, this behavior is intentional at the moment. Patches with implementation (i.e. for Gnome) are welcome.

**Comment by DevSrSouza** [comment]
I did create a simple gist trying to guess the theme by the GTK Theme, it could be useful.
https://gist.github.com/DevSrSouza/1b0c3840c9d0b62e8b7bba38ecaebb5f

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-403">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
