### ISSUE TITLE
Attaching SkiaLayer to a JComponent instead of window.contentPanel

### ISSUE THREAD

**Issue by IvanEFan** [JetBrains/skiko#428]
I want to create a window with a `SkiaLayer` and a `JButton`. I tried the code below:

```kotlin
SwingUtilities.invokeLater {
        val window = JFrame("skiko").apply {
            defaultCloseOperation = WindowConstants.EXIT_ON_CLOSE
            preferredSize = Dimension(800, 600)
        }
        val panel = JPanel()
        skiaLayer.attachTo(panel)
        skiaLayer.needRedraw()
        window.add(panel)

        val button = JButton("test")
        window.add(button)

        window.pack()
        window.isVisible = true
    }
```

However, only the button is rendered and filled all the places:

![image](https://user-images.githubusercontent.com/83502019/145505261-226f9eaa-bad7-496b-873c-3e377f79606e.png)

If I remove the button, the `SkiaLayer` is still not being rendered

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-428">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
