### ISSUE TITLE
Allow change path to cacheRoot

### ISSUE THREAD

**Issue by kinosang** [JetBrains/skiko#432]
for e.g., use XDG_CONFIG or other environment variables.

**Comment by olonho** [comment]
Could you please explain your scenarious. Why `skiko.library.path` is not enough.

**Comment by kinosang** [comment]
@olonho does Fleet support change `skiko.library.path` property?

**Comment by olonho** [comment]
Guess it better be asked from Fleet team.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-432">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
