### ISSUE TITLE
Support for kotlin-native for Mingw_XX

### ISSUE THREAD

**Issue by caffeine-mgn** [JetBrains/skiko#446]
In https://github.com/JetBrains/skiko/blob/master/skiko/build.gradle.kts missing build for mingw.

**Comment by olonho** [comment]
Yes, Windows native build is not supported.

**Comment by caffeine-mgn** [comment]
Hm, ok. Can you add support for windows? :) Some people use Windows to develop. Other people use Windows for run some program

**Comment by olonho** [comment]
Windows is supported in JVM builds.

**Comment by caffeine-mgn** [comment]
> Windows is supported in JVM builds.

I'm saying about kotlin-native. Can you add support for kotlin-native? I want to use native, I want to write windows application without any jvm

**Comment by olonho** [comment]
Please report an issue for Kotlin/Native to allow static linking with MSVC-compiled libraries, otherwise we cannot link Skia libraries into K/N binary on Windows.

**Comment by caffeine-mgn** [comment]
Why you don't use clang compiler for building Skia? Why MSVC? You can use something like this https://github.com/caffeine-mgn/kn-clang-compiler-plugin. This plugin allows using clang from konan

**Comment by Syrou** [comment]
*bump* would love to see this

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-446">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
