### ISSUE TITLE
Investigate how to properly handle vsync with multiple displays

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#45]
Vsync with multiple monitors works (https://github.com/JetBrains/skiko/pull/44), but not ideally (because we use single thread on Windows/Linux to wait for vsync, so we wait for the slowest/fastest (depends on a platform) display

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-45">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
