### ISSUE TITLE
Start signing skiko maven artifacts

### ISSUE THREAD

**Issue by liutikas** [JetBrains/skiko#456]
Almost all of org.jetbrains libraries are [signed](https://central.sonatype.org/publish/requirements/#sign-files-with-gpgpgp) with .asc signatures allowing to validate if these libraries were built by Jetbrains. It would be great if skiko started signing the artifacts as well so their builder could be verified as well.

**Comment by liutikas** [comment]
Actually nevermind, they look to be signed https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/skiko/skiko/0.7.2/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
