### ISSUE TITLE
More accurate vsync

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#46]
Vsync (https://github.com/JetBrains/skiko/pull/44) doesn't work ideally.

After tests in Compose (./gradlew runVsync) we discovered that we miss a frame every 2-10 sec

Figure out how we can implement ideal vsync without missed frames

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-46">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
