### ISSUE TITLE
Draw bytes on canvas

### ISSUE THREAD

**Issue by igr** [JetBrains/skiko#478]
I get the canvas bytes like this:

```kt
bitmap.peekPixels()!!.buffer.bytes
```

I then manipulate bytes etc. Then, I want to update the whole canvas with the bytes, but I can't create an `Image` from raw bytes

```kt
val i = Image.makeFromEncoded(bytes)	// exception
val i = Image.makeFromPixmap(Pixmap.make(ImageInfo.DEFAULT, Data.makeFromBytes(this.bytes),this.bytes.size)) // exception
canvas.drawImage(i, 0f, 0f)
```

How to create an image from the raw bytes?

**Comment by igr** [comment]
``` this.bitmap.installPixels(this.bytes)``` solves

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
