### ISSUE TITLE
Possible null pointer dereference in Shaper::shapeLine

### ISSUE THREAD

**Issue by VeselovAlex** [JetBrains/skiko#485]
In Shaper::shapeLIne `font` is declared nullable, but dereferenced in native code without null check.

**Comment by VeselovAlex** [comment]
resolved with #499

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-485">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
