### ISSUE TITLE
How to enable code highlight/redirection for cpp code?

### ISSUE THREAD

**Issue by linroid** [JetBrains/skiko#492]
I see the cpp code are compiled by custom commands in `CompileSkikoCppTask`, code highlight for cpp (e.g. under the `skiko/src/jvmMain/cpp/common` folder) doesn't work perfectly when I opening this project in IntelliJ IDEA or CLion.

So how to make this works? thanks!

**Comment by linroid** [comment]
> Not sure if this is related to Skiko per se.

Thanks for reply ❤️, I'm curious about how you edit the cpp code for Skiko, are you editing them as plain text or using other editors like vim/vsc? @Schahen @olonho @eymar may know the answer as they are the contributors. I see no [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) is generated, both IDEA and CLion are not working correctly on code highlight for cpp code,

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-492">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
