### ISSUE TITLE
renderInfo is not accurate

### ISSUE THREAD

**Issue by adorokhine** [JetBrains/skiko#493]
SkiaLayer.info prints the requested API regardless of which API was chosen. For example, trying DIRECT3D on Linux happily prints:
```
GraphicsApi: DIRECT3D
OS: linux x64
Vendor: Intel
Model: Mesa Intel(R) UHD Graphics (CML GT2)
Total VRAM: 31 MB
```

I have stepped into it with a debugger and confirmed that the chosen API was actually LinuxOpenGLRedrawer.

I think renderInfo should accurately represent what was actually chosen so that meaningful performance comparisons can be made.

skiko-awt-linux-x64 0.7.7.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
