### ISSUE TITLE
Performance characteristics of skiko AWT on Linux + OpenGL are not good

### ISSUE THREAD

**Issue by adorokhine** [JetBrains/skiko#494]
General advice for dealing with Swing UI (and UI in general) is to render into a backbuffer, then swap the buffers.

Before I switched to Skiko, I drew into a java.awt.Canvas which I could swap:
http://www.cokeandcode.com/info/tut2d.html

However, Skiko draws and renders everything on the UI thread:
1. https://github.com/JetBrains/skiko/blob/8e84e9e0de320ce5fbcb775b701504cc6a38db00/skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt#L419
2. https://github.com/JetBrains/skiko/blob/8e84e9e0de320ce5fbcb775b701504cc6a38db00/skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt#L472
3. https://github.com/JetBrains/skiko/blob/c8bdf96a208cb3e379108076214d61309e66f3c5/skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt#L80

This problem is exacerbated by the fact that Skiko's default settings submit the next redraw request as soon as the old one finishes, so regardless of how fast drawing actually happens, swing's UI thread is constantly swamped with Skiko rendering:
https://github.com/JetBrains/skiko/blob/2d49c2625cf176240a1f9537de63f5a87b965cf1/skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkikoView.kt#L27

Swing uses the UI thread for drawing its own UI and especially for handling input events. Skiko's behaviour of swamping the UI thread creates significant input event lag. Even though Skiko's rendering is faster than what I had before, the UI is much laggier because it takes a lot longer for the event thread to pick up the input events, so the program takes a long time to respond to input.

I would suggest the following fixes:
1. Don't request redraw immediately after rendering. Use a rate limiter or let the client program drive Skiko with its own event loop.
2. Perform rendering off the event thread, into a back buffer. This way, even if rendering is slow (which it sometimes is for large scenes and slow hardware), input is still handled quickly and the UI remains snappy.

**Comment by adorokhine** [comment]
(Here's where it spends most of its time in the event thread:)

![image](https://user-images.githubusercontent.com/2999402/153836804-1f15aa28-0423-4753-aaa0-518e05242b0a.png)

**Comment by olonho** [comment]
https://github.com/JetBrains/skiko/pull/351 may somewhat help here.

**Comment by olonho** [comment]
Also note that Skiko on different platforms and backends behaves differently, so it would be better to describe OS and drawing backend used.

**Comment by adorokhine** [comment]
Thanks! This is Skiko 0.7.7 on Linux OpenGL

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-494">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
