### ISSUE TITLE
Stuttering/long frame times

### ISSUE THREAD

**Issue by mworzala** [JetBrains/skiko#496]
I assume that I am doing something wrong here, but I am experiencing some pretty noticeable stuttering.

Here is a video of what is happening, and the rendering code used
https://user-images.githubusercontent.com/35708499/153926341-26b573ba-1e8e-4d6c-90c2-205bf683d1e2.mov

```kotlin
var frame: Int = 0
override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
    canvas.clear(0x00000000)

    frame += 1
    Paint().use { paint ->
        paint.color = 0xFFFF0000.toInt()
        canvas.drawRect(Rect.makeXYWH(0f, 0f, frame.toFloat() * 2, 100f), paint)
    }
}
```

**Comment by olonho** [comment]
Without OS/renderer/hardware information it's pretty hard say anything. Are Skiko samples work fast on your machine?

**Comment by olonho** [comment]
Also I'd use `(frame * 2 % width).toFloat()` here.

**Comment by mworzala** [comment]
It was happening with the samples as well, but I cannot reproduce anymore. Will close for now

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-496">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
