### ISSUE TITLE
Android. Long input lag during animations

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#498]
Currently we draw animation frames this way:

![image](https://user-images.githubusercontent.com/5963351/153936983-f19e3e9d-02c5-4c1c-bae8-3cfd094c9822.png)

and have one lag-frame between input (click) and displaying reaction to this input:
click -> vsync -> update -> vsync -> draw -> vsync -> show picture on display.

To reduce input lag by one frame we can start to update in the beginning of the frame:
click -> vsync -> update -> draw -> vsync -> show picture on display

![image](https://user-images.githubusercontent.com/5963351/153937282-c91b65e2-726a-4521-8ff5-0d76d075cd86.png)

There is still one frame lag though, which desktop renderers have too. We probably can't get rid of one-frame lag because of the nature of vsync.

**Comment by olonho** [comment]
Not sure if this one is too important to work on it soon, considering current perceived Android performance.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-498">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
