### ISSUE TITLE
Search fonts in classpath resources

### ISSUE THREAD

**Issue by lamba92** [JetBrains/skiko#507]
See [jewel/issues/4](https://github.com/JetBrains/jewel/issues/4).

**Comment by olonho** [comment]
See https://github.com/JetBrains/skiko/pull/509

**Comment by olonho** [comment]
@lamba92 does it work for you?

**Comment by rock3r** [comment]
@lamba92 can you please confirm whether this works now?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-507">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
