### ISSUE TITLE
How convert AVFrame to Skia Image

### ISSUE THREAD

**Issue by habibg1232191** [JetBrains/skiko#508]
I'm trying to make a player on ffmpeg([javacv](https://github.com/bytedeco/javacv)). But I can't decode avframe to skia image. Here is an example [code](https://github.com/google/skia/blob/main/experimental/ffmpeg/SkVideoDecoder.cpp) in c++ skia and ffmpeg. I don't know how to write it in kotlin.

My not working [code](https://gist.github.com/habibg1232191/c3bcafb22ffcc17132c1a590f97e6b5c)

**Comment by kirill-grouchnikov** [comment]
You've asked this in the kotlin lang slack. 

Skiko exposes a subset of Skia APIs via Kotlin bindings. Is there a specific API binding that is missing? If not, you go line by line and convert the C++ code to the matching Kotlin bindings that are a one-to-one mappings to the underlying Skia APIs.

**Comment by kirill-grouchnikov** [comment]
```
//                  How can I write this in kotlin?
//                  uint8_t*   dst[] = { (uint8_t*)bm.pixmap().writable_addr() };
//                  int dst_stride[] = { SkToInt(bm.pixmap().rowBytes()) };
```

I pointed you to the bindings: https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt#L993 is the binding to SkBitmap.pixmap(). https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Pixmap.kt#L99 is the binding to rowBytes().

**Comment by kirill-grouchnikov** [comment]
Sometimes a certain C++ construct is not going to be necessary, like `writeable_addr` call - see [// methods related to C++ types(addr8/16/32/64, writable_addr8/16/32/64) not included - not needed
](https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Pixmap.kt#L385)

**Comment by habibg1232191** [comment]
How do i write pixmap to bitmap?
[Here](https://gist.github.com/habibg1232191/c3bcafb22ffcc17132c1a590f97e6b5c#file-composeffmpeg-kt-L91) there is a method to which you need to pass ptr pixmap. As shown [here](https://github.com/google/skia/blob/main/experimental/ffmpeg/SkVideoDecoder.cpp#L248)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
