### ISSUE TITLE
Android armeabi-v7a support?

### ISSUE THREAD

**Issue by thaihuynhxyz** [JetBrains/skiko#514]
![Screen Shot 2022-03-08 at 17 01 27](https://user-images.githubusercontent.com/29724810/157213790-78f7b634-3574-42a4-b151-f9525bf54aac.png)
Do we have a plan to support armeabi-v7a on Android?

**Comment by olonho** [comment]
No, 32-bit x86 is not supported in Skiko. Please use x86-64 simulators.
