### ISSUE TITLE
SVG data parsing results in IllegalArgumentException

### ISSUE THREAD

**Issue by pusolito** [JetBrains/skiko#518]
The following is valid SVG data and works in this [fiddle](https://fiddle.skia.org/c/0feedb04234d4d7b477beb431dfaa24b).

"M12.5 11H11.71L11.43 10.73A6.471 6.471 0 0013 6.5 6.5 6.5 0 106.5 13C8.11 13 9.59 12.41 10.73 11.43L11 11.71V12.5L16 17.49 17.49 16 12.5 11ZM6.5 11C4.01 11 2 8.99 2 6.5S4.01 2 6.5 2 11 4.01 11 6.5 8.99 11 6.5 11Z"

However, it fails to parse in 0.7.16.

file: .../commonMain/org/jetbrains/skia/Path.kt

```kotlin
fun makeFromSVGString(svg: String): Path  {
    Stats.onNativeCall()
    val result = interopScope {
        _nMakeFromSVGString(toInterop(svg))
    }

    if (result == NullPointer) {
       throw IllegalArgumentException("Failed to parse SVG Path string: $svg") // <=========== Gets here b/c result is NullPointer
    } else {
        return Path(result)
    }
 }
```

**Comment by pusolito** [comment]
Any updates on this issue? It is a blocker for apps that rely on SVG.

**Comment by Nekoyue** [comment]
Found a possible cause/fix for this issue. It seems like a formatting issue with non-standard representations of [arcs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#arcs). The code will work after adding spaces like the image below. Some SVG optimization tools (e.g. https://www.svgviewer.dev/ ) may be able to do this automatically.
<img width="754" alt="image" src="https://user-images.githubusercontent.com/46295491/167735253-6454f5d5-9b9b-403c-86c9-b71f39a3e363.png">

**Comment by pusolito** [comment]
Thanks for following up. These changes resolved my issue. It's interesting that some engines are more lenient in their parsing. But it makes more sense to have clean inputs when possible.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-518">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
