### ISSUE TITLE
Add bindings for SkImageFilters::RuntimeShader

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/skiko#519]
Android 13 has [added an API](https://developer.android.com/reference/android/graphics/RenderEffect#createRuntimeShaderEffect(android.graphics.RuntimeShader,%20java.lang.String)) to create a render effect that gets the content of the underlying render node and passes it to the shader. This enables running a shader on top of any node in the view hierarchy.

In Compose, this is then exposed via `asComposeRenderEffect` - for the Android platform.

The counterpart for the desktop variant is to add bindings to the recently added `SkImageFilters::RuntimeShader`. There are two variants, with one and multiple nodes. The first was added in m98, and the second in m99. Skiko has been using m99 since January 2022.

The proposal (and the forthcoming PR) is to add bindings to these Skia APIs that should allow running Skia shaders on any node in the desktop compose view hierarchy, in addition to what is already available from the core bindings in `ImageFilter.cc` (like blend, blur, color filter, etc).

**Comment by kirill-grouchnikov** [comment]
In the screenshot below, the two buttons in the middle row have runtime shaders applied via `renderEffect`:

* The left button has a simple shader that looks at the underlying render node and bumps the red channel to max
* The right button has a more complex shader. This shader is built from two child nodes:
    * One that looks at the underlying render node and bumps the red channel to max
    * Blur created with an existing `ImageFilter.makeBlur` binding
    * And this shader also has a float uniform that specifies the cutoff point between the two child shaders

<img width="346" alt="runtime-shader-effect" src="https://user-images.githubusercontent.com/52874/160284256-dd52fec0-e913-4328-92f2-ad12fdcf9d89.png">

The code for the first one, using the new bindings for `SkRuntimeShaderBuilder` constructor and `SkImageFilters::RuntimeShader`:

```
    val redSksl = """
        uniform shader content;
        vec4 main(vec2 coord) {
            vec4 c = content.eval(coord);
            return vec4(1.0, c.g, c.b, c.a);
        }
        """

    val redRuntimeEffect = RuntimeEffect.makeForShader(redSksl)
    val redShaderBuilder = RuntimeShaderBuilder(redRuntimeEffect)

    ...

    Modifier.graphicsLayer(
            renderEffect = ImageFilter.makeRuntimeShader(
                  runtimeShaderBuilder = redShaderBuilder,
                  shaderName = "content",
                  input = null
            ).asComposeRenderEffect()
```

The code for the second one using the new bindings for `SkRuntimeShaderBuilder::uniform` and the second variant of `SkImageFilters::RuntimeShader` that gets multiple inputs:

```
    val blurSksl = """
        uniform shader content;
        uniform shader blurred;
        uniform float cutoff;
        vec4 main(vec2 coord) {
            vec4 c = content.eval(coord);
            vec4 b = blurred.eval(coord);
            if (coord.x > cutoff) {
                return vec4(1.0, c.g, c.b, c.a);
            } else {
                return b;
            }
        }
        """

    val blurRuntimeEffect = RuntimeEffect.makeForShader(blurSksl)
    val blurShaderBuilder = RuntimeShaderBuilder(blurRuntimeEffect)
    blurShaderBuilder.uniform("cutoff", 100.0f)
    val blurImageFilter = ImageFilter.makeBlur(sigmaX = 2.0f, sigmaY = 2.0f, mode = FilterTileMode.DECAL)

    ...

    Modifier.graphicsLayer(
            renderEffect = ImageFilter.makeRuntimeShader(
                   runtimeShaderBuilder = blurShaderBuilder,
                   shaderNames = arrayOf("content", "blurred"),
                   inputs = arrayOf(null, blurImageFilter)
            ).asComposeRenderEffect() 
```

**Comment by kirill-grouchnikov** [comment]
Screenshot with better visuals - applying the render effect on a slightly larger box so that the blur is not cropped by button bounds

<img width="346" alt="runtime-shader-effect2" src="https://user-images.githubusercontent.com/52874/160285924-7296c76f-fc01-437b-91c8-06dc628e07fe.png">

**Comment by kirill-grouchnikov** [comment]
#520 + #524 + #526 have been merged. Closing this as fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-519">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
