### ISSUE TITLE
OpenGL Rendering

### ISSUE THREAD

**Issue by abueide** [JetBrains/skiko#522]
Hi I really love compose and want to use it for the GUI in my game. If anyone has some offhand information on how to tackle either rendering compose into an existing opengl context with lwjgl3 or taking framebuffer data from the opengl context and rendering it with skiko, please let me know. I'd love to tackle this but I just don't know where to get started.

Thanks!

**Comment by smallshen** [comment]
@abueide https://github.com/semoro/JetpackComposeMinecraft/blob/1.17.1/src/main/kotlin/club/eridani/client/TestGui.kt
this is an example.
My team is working on OpenGL integration with Jetpack Compose(use skiko under the hood), we will open-source it once stable.

**Comment by jdw** [comment]
What was the outcome?

**Comment by kirill-grouchnikov** [comment]
Doesn't look like there was any movement in that project since October 2021

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-522">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
