### ISSUE TITLE
Missing architecture arm64 when running kmp sample

### ISSUE THREAD

**Issue by kdaker** [JetBrains/skiko#527]
I'm trying to run the `SkiaMultiplatformSample` on an M1 mac and it seems like it's not using the correct architecture. I get this (with cache disabled):

```
ld: warning: ignoring file /var/folders/xw/xfy1msn927ld5g7mvbln4f8m0000gn/T/included7320680627984216260/skiko-native-bridges-macos-arm64.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_org_jetbrains_skia_impl_RefCnt__getFinalizer", referenced from:
      _kfun:org.jetbrains.skia.impl.RefCnt._FinalizerHolder.<init>#internal in result.o
      ...
```

When I lipo that `.a` file I get an x86 architecture:

```
lipo -info /var/folders/xw/xfy1msn927ld5g7mvbln4f8m0000gn/T/included7320680627984216260/skiko-native-bridges-macos-arm64.a
Non-fat file: /var/folders/xw/xfy1msn927ld5g7mvbln4f8m0000gn/T/included7320680627984216260/skiko-native-bridges-macos-arm64.a is architecture: x86_64
```

I'm running the `runNative` task but I get the same issue for all `macArm64` tasks.

**Comment by kdaker** [comment]
Ok so it seems like I was on the wrong JDK. I was on apple silicon version of 11. I switched to the regular jdk11 and now it runs but it's using the X86 binaries and running as an intel process. Is this expected?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-527">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
