### ISSUE TITLE
Add ability to redraw only part of the buffer

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#53]
Usually we don't need to redraw the whole window .

This can significantly increase performance in many cases when the only a small part of the screen is changed.
For example, if only ProgressBar is animated in some part of the screen, or we hover some button.

API will be as:
```
fun needRedraw(rect: Rect? = null) {

}
```

SkiaRenderer API should stay the same.

After multiple needRedraw's we will intersect all rects into one bigger rect and clip canvas by it when we start to draw the content.

We should take into account that different graphics backends manipulate buffers differently.
And also we should take into account that we use double-buffering, so we can't reuse the old buffer, because it will have a wrong content.

**Comment by olonho** [comment]
Also likely need proper testing for that, current Skiko sample makes the whole screen dirty on every frame.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-53">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
