### ISSUE TITLE
Request for examples of Android target in a KMP project

### ISSUE THREAD

**Issue by iKozlinskyi** [JetBrains/skiko#531]
Hello!
I would like to use Skiko in a cross-platform library for apps targeting Web, Android, and iOS.  I see [an example of KMP+Skiko project](https://github.com/JetBrains/skiko/tree/master/samples/SkiaMultiplatformSample), and also [an Android+Skiko example](https://github.com/JetBrains/skiko/tree/master/samples/SkiaAndroidSample). But I struggle to integrate a KMP+Skiko library with an Android project. This seems like a rookie question, but I encountered various problems trying to use the multiplatform library and an android project having both Skiko as a dependency. It would be great if you also updated the KMP+Skiko example with an Android target.

**Comment by vrublevskys** [comment]
Join the issue. Anybody can implement `androidMain` in [Multiplatform sample](https://github.com/JetBrains/skiko/tree/master/samples/SkiaMultiplatformSample)? It is matter of life and death for me 🥺

**Comment by vrublevskys** [comment]
Seems like I solved my problem by `compileOnly`. Example below:
```
    sourceSets {
        val commonMain by getting {
            dependencies {
                compileOnly("org.jetbrains.skiko:skiko:$version")
            }
        }

        val androidMain by getting {
            dependsOn(commonMain)
            dependencies {
                implementation("org.jetbrains.skiko:skiko-android:$version")
            }
        }
```
Before this, I had a problem with 'Duplicate class' error

**Comment by hbrtose** [comment]
Hi, I tried to implement this, but I'm still seeing this error:
```
Unable to resolve dependency for %27%3Ashared%40debug%2FcompileClasspath%27%3A Could not resolve org.jetbrains.skiko%3Askiko%3A0.7.37.


Could not resolve org.jetbrains.skiko:skiko:0.7.37.
Required by:
    project :shared
 > The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.3', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of org.jetbrains.skiko:skiko:0.7.37:
     - androidApiElements-published
     - androidRuntimeElements-published
     - awtApiElements-published
     - awtRuntimeElements-published
     - samplessources
   All of them match the consumer attributes:
```

The build.gradle.kts is:
```
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization") version "1.7.20"
    id("com.android.library")
}

val coroutinesVersion = "1.5.2"
val skikoVersion = "0.7.37"
val serialization_version = "1.4.1"

kotlin {
    android() {
        publishLibraryVariants("release", "debug")
    }
}

sourceSets {
        val commonMain by getting {
            dependencies {
                compileOnly("org.jetbrains.skiko:skiko:$skikoVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$serialization_version")
            }
        }
        val commonTest by getting {
            dependencies {
                dependsOn(commonMain)
                implementation(kotlin("test"))
            }
        }
        val androidMain by getting {
            dependencies {
                dependsOn(commonMain)
                implementation("org.jetbrains.skiko:skiko-android:$skikoVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion")
            }
        }
        val androidTest by getting
}
```

**Comment by gandrewstone** [comment]
skiko 0.7.93 or 0.8.4:

On android I am getting this (but it works on JVM):
Rejecting re-init on previously-failed class java.lang.Class<org.jetbrains.skia.Image>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/...==/base.apk"],nativeLibraryDirectories=[/data/app/...==/lib/arm64, /data/app/...==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libskiko-android-arm64.so"

This is a multiplatform gradle project.  I've tried "compileOnly" and "implementation" in commonMain:
```compileOnly("org.jetbrains.skiko:skiko:$skikoVersion")```

In my androidMain I've tried these:

```
implementation("org.jetbrains.skiko:skiko-android:$skikoVersion")
//implementation("org.jetbrains.skiko:skiko-android-runtime-x64:$skikoVersion")
//implementation("org.jetbrains.skiko:skiko-android-runtime-arm64:$skikoVersion")
```

anybody successfully using skiko outside of compose in multiplatform?

**Comment by Siedlerchr** [comment]
Yes, we use it in kmp (jvm+ android)  providing the libraries with runtimeOnly

**Comment by kexuejin** [comment]
> Yes, we use it in kmp (jvm+ android) providing the libraries with runtimeOnly

Can you use the version 0.8.4?

**Comment by kexuejin** [comment]
> SKIKO 0.7.93 或 0.8.4：
> 
> 在 android 上，我收到这个（但它在 JVM 上有效）：拒绝之前失败的类 java.lang.Class<org.jetbrains.skia.Image>的重新初始化：java.lang.UnsatisfiedLinkError： dalvik.system.PathClassLoader[DexPathList[[zip file “/data/app/...==/base.apk”]，nativeLibraryDirectories=[/data/app/...==/lib/arm64， /data/app/...==/base.apk！/lib/arm64-v8a， /system/lib64， /system/product/lib64]]] 找不到“libskiko-android-arm64.so”
> 
> 这是一个多平台 gradle 项目。我尝试了 commonMain 中的“compileOnly”和“implementation”： `compileOnly("org.jetbrains.skiko:skiko:$skikoVersion")`
> 
> 在我的 androidMain 中，我尝试了这些：
> 
> ```
> implementation("org.jetbrains.skiko:skiko-android:$skikoVersion")
> //implementation("org.jetbrains.skiko:skiko-android-runtime-x64:$skikoVersion")
> //implementation("org.jetbrains.skiko:skiko-android-runtime-arm64:$skikoVersion")
> ```
> 
> 有人在 Multiplatform 的 Compose 之外成功使用 SKIKO 吗？

I have temporarily solved this problem, you can refer to https://github.com/JetBrains/skiko/issues/761

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-531">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
