### ISSUE TITLE
cannot find skiko-windows-x64.dll.sha256

### ISSUE THREAD

**Issue by ynsok** [JetBrains/skiko#533]
Hi, 

After trying to run the project on windows, this error occurs 

![image](https://user-images.githubusercontent.com/30358511/168541940-87b587e0-f57e-41a7-b18c-7a3f4f2a1ec5.png)

Any Idea what is wrong?  @prepor @yole @kirill-grouchnikov @topka @shafirov

**Comment by yole** [comment]
Please avoid `@`-mentioning random people not involved in the project in any way.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-533">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
