### ISSUE TITLE
Write to a non visible canvas to create an image

### ISSUE THREAD

**Issue by Octoate** [JetBrains/skiko#539]
Hi,
I currently stumbled upon the Skiko library and I am trying to get into the API of it. What I want to implement is a small rendering service, that takes some texts and images, renders them to a canvas and produces an image that can be either displayed in an application (Android) or stored on disk for later usage (Linux / Windows).
I already had a look at the examples but it seems that they all use the targets UI elements to render stuff to it.
Is it possible to create a canvas with a given size and render e.g. some text to it? If so, how can I start? Do I need to start with a SkiaLayer and how to set the size for the canvas than?

Any help is highly appreciated :-).

**Comment by Octoate** [comment]
Well, I made some progress here: I create a Surface, get the Canvas from it and draw on this canvas. After that, I make a snapshot of the surface and encode the image as PNG. Works fine.
However, since this functionality shall be provided by a library, I have to include Skiko in this library. Is it necessary to provide the library for all the platforms that it shall support and have to compile it for each of the platforms? Or is there a common Skiko layer that I can include and add the necessary runtime files in the platform specific implementation (e.g. in Android or in the JVM AWT on the server side)?

**Comment by mcpiroman** [comment]
Please take a look at releases or readme, there is a precompiled artifact for each supported platform.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-539">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
