### ISSUE TITLE
Support Windows prior to Windows10 - User32.dll::GetDpiForWindow

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/skiko#540]
Loading skiko-windows-x64.dll on Windows Server 2012 throws some kind of `UnsatisfiedLinkException`, "`The specified procedure cound not be found`" in my case.

As I have found out it is because of missing a function [`GetDpiForWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow) in `User32.dll`. According to docs this function has:
<html>
<body>

Minimum supported client | Windows 10, version 1607 [desktop apps only]
-- | --
Minimum supported server | None supported

</body>
</html>

It looks like it is the only missing function (on srv2012 at least), so by making it an dynamic dependency some older Windows versions could be supported.
Note that it is used only once in the skiko codebase and only as a fallback, so it may be not that hard to get away without it. Skia seems to support Windows 7 upwards.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-540">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
