### ISSUE TITLE
Also set `ui` attribute for the other jvm targets, and give it a namespace

### ISSUE THREAD

**Issue by jakobkmar** [JetBrains/skiko#547]
The [`ui` attribute](https://github.com/JetBrains/skiko/blob/5ad212b53e08a1aaf6658a7a602ce38f78d0648f/skiko/build.gradle.kts#L222), which is currently set for the jvm Android target, should also be set for the other UI targets, so that consumers can specifically ask for the awt target for example.

Additionally, it might be a good idea to give the attribute a namespace, like `org.jetbrains.skiko.ui`, since all other attributes have one. And `ui` is very common.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-547">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
