### ISSUE TITLE
Vulkan bindings

### ISSUE THREAD

**Issue by smallshen** [JetBrains/skiko#549]
Skia supports vulkan (https://skia.org/docs/user/special/vulkan/)
Are there any plans to add bindings for the vulkan api?

**Comment by ygdrasil-io** [comment]
Any update ? Roadmap regarding Vulkan support ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-549">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
