### ISSUE TITLE
Traces after we remove SkiaLayer from some swing container

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#551]
Skiko 0.7.21, macOs

See the video, the tab "dotMemory Profiler" uses SkiaLayer. After we switch to another tab, the SkiaLayer content still on the screen until we resize the whole window.

https://user-images.githubusercontent.com/5963351/178004441-2e00d36a-104b-4b7c-894e-5ef643a3a6db.mov

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-551">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
