### ISSUE TITLE
Blinking when we create SkiaLayer for the first time inside some Swing application

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#553]
Skiko 0.7.21

See the video, the whole IDEA window is blinking on the 7th second

https://user-images.githubusercontent.com/5963351/178012368-30e9af60-4fe7-4ac4-8806-8a6eda0fd11d.mp4

(if I record directly, not with smartphone, it isn't noticeable)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-553">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
