### ISSUE TITLE
Incorrect layout on Windows

### ISSUE THREAD

**Issue by NorbertSandor** [JetBrains/skiko#556]
On Windows 11, when _System > Display > Scale & Layout > Scale_ is set to 125% (the recommended value on my system) then the entire view is shifted to the top by 1 pixel:

![image](https://user-images.githubusercontent.com/2658625/179526959-9d2f2ab1-a1c0-42a1-b698-7493824ece86.png)

Local-device matrix:
```
1.25 0    0
0    1.25 0
0    0    1
```

If the system _Scale_ is set to 100%, it works as expected:

![image](https://user-images.githubusercontent.com/2658625/179527694-cd6242c0-3549-42d6-b3cc-091cce1d8f6a.png)

Local-device matrix: identity

Ugly code:
```
fun main() {
    val skiaLayer = SkiaLayer()
    skiaLayer.skikoView = GenericSkikoView(skiaLayer, object : SkikoView {
        val redPaint = Paint().apply {
            color = Color.RED
        }

        override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
            canvas.clear(Color.WHITE)
            canvas.drawLine(0f, 0f, (width - 1).toFloat(), 0f, redPaint)
            canvas.drawLine((width - 1).toFloat(), 0f, (width - 1).toFloat(), (height - 1).toFloat(), redPaint)
            canvas.drawLine((width - 1).toFloat(), (height - 1).toFloat(), 0f, (height - 1).toFloat(), redPaint)
            canvas.drawLine(0f, (height - 1).toFloat(), 0f, 0f, redPaint)
        }
    })
    SwingUtilities.invokeLater {
        val window = JFrame("Skiko example").apply {
            defaultCloseOperation = WindowConstants.EXIT_ON_CLOSE
            preferredSize = Dimension(2560 / 8, 1440 / 8)
        }
        skiaLayer.attachTo(window.contentPane)
        skiaLayer.needRedraw()
        window.pack()
        window.isVisible = true
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-556">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
