### ISSUE TITLE
Immediate fallback to software rendering

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#57]
Now we don't immediately switch to software rendering when hardware isn't available
```
start -> needRedraw -> draw (hardware) -> needRedraw -> scheduleFallbackToRaster -> draw (hardware) -> scheduleFallbackToRaster -> draw (software)
```
Figure out can we switch to software rendering before first draw.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-57">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
