### ISSUE TITLE
GraalVM: native image from skiko application  throws error: cannot open (null)/lib/libjawt.so

### ISSUE THREAD

**Issue by AlexanderScherbatiy** [JetBrains/skiko#580]
The original issue has been reported at https://github.com/bell-sw/LibericaNIK/issues/14

Native image, built by GraalVM, does not define `java.home` java property so dynamic `jawt` lib loading fails on Linux and MacOS in code https://github.com/JetBrains/skiko/blob/c08102bbf9742c920c4ce6e90bffc09c5a202772/skiko/src/jvmMain/cpp/common/jawt.cc#L88

The proposed solution could be to link skiko lib with `jawt` lib statically only for native image generation.

Steps to reproduce:
- Update SkiaAwtSample `build.gradle.kts` to create uber jar:
```
plugins {
    kotlin("jvm") version "1.6.10"
    application
    id("com.github.johnrengelman.shadow") version "7.1.2"
}
```
- Create an uber jar `gradle build`
- Run SkiaAwtSample with GraalVM native image agent to generate configuration files with JNI, reflections, and resources:
```
<graalvm>/bin/java -agentlib:native-image-agent=config-output-dir=conf-dir -jar build/libs/SkiaAwtSample-all.jar
```
- Build a native image with GraalVM
```
<graalvm>/bin/native-image -Djava.awt.headless=false -H:ReflectionConfigurationFiles=conf-dir/reflect-config.json -H:JNIConfigurationFiles=conf-dir/jni-config.json -H:ResourceConfigurationFiles=conf-dir/resource-config.json -jar build/libs/SkiaAwtSample-all.jar
```
- Run the generated native image:
```
./SkiaAwtSample-all 
Cannot open (null)/lib/libjawt.so: (null)/lib/libjawt.so: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

The fix could consist of two steps.
First, change the dynamic `jawt` lib loading to link skiko lib with jawt.  As an example, the draft solution tested on Linux only: https://github.com/AlexanderScherbatiy/skiko/commit/94b709724273e519bcc24315294825a7e88d9ca9
Second, if the first step is accepted, add an option which links with jawt lib statically to make it possible to generate a native image by GraalVM. It would need to use static jawt library from GraalVM and its dependencies, like:
```
           OS.Linux -> {
                osFlags = arrayOf(
                   ...
                    "-l:libjawt.a",
                    "-l:libawt_xawt.a",
                    "-l:libawt.a",
                    "-l:libjava.a",
                    "-L$jdkHome/lib",
```
where jdkHome is path to GraalVM.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-580">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
