### ISSUE TITLE
RuntimeShaderBuilder API - makeShader

### ISSUE THREAD

**Issue by mandarin6b0** [JetBrains/skiko#590]
It seems that RuntimeShaderBuilder.kt has no [makeShader](https://github.com/google/skia/blob/main/include/effects/SkRuntimeEffect.h#L480) method now. Can we expect this to be added in future?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-590">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
