### ISSUE TITLE
Unexpected result from Path.convertConicToQuads()

### ISSUE THREAD

**Issue by amarland** [JetBrains/skiko#592]
I suspect `Path.convertConicToQuads()` always returns an incomplete array of points.

Looking at its implementation, I notice it uses the return value of Skia's [`ConvertConicToQuads()` method](https://api.skia.org/classSkPath.html#a85edbc9299283aa955772764e30598dd) to determine the size of the returned array, which I believe is erroneous given the Skia docs state this number indicates the "number of quad curves" that can be formed with the points, not the number of points written to the destination array.

This becomes clearer when looking at examples such as this [fiddle](https://fiddle.skia.org/c/@Path_ConvertConicToQuads) or this [SkiaSharp sample](https://github.com/mono/SkiaSharp/blob/main/samples/Gallery/Shared/Samples/PathConicToQuadsSample.cs).
If we compare the fiddle with [this statement from `PathTests.kt`](https://github.com/JetBrains/skiko/blob/9372822baefe561f3c653a978532addc183d9ff6/skiko/src/commonTest/kotlin/org/jetbrains/skia/PathTests.kt#L205), we can see that passing `1` as the value for parameter `pow2` results in 5 (1 + 2 * `pow2`²) points being written to/read from `quads`, while the test expects only 2. This is most likely wrong as even with 1 quad curve (`pow2 = 0`), I believe there should be 3 points: 1 start point + 2 control points.

Example:
```kotlin
Path.convertConicToQuads(Point(0f, 40f), Point(0f, 52f), Point(12f, 52f), 0.70710677f, 1)
```
If we debug the above call and add a breakpoint [here](https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Path.kt#L155), before the function returns, the result of `coords.contentToString()` is:
```kotlin
"[0.0, 40.0, 0.0, 44.97056, 3.5147185, 48.485275, 7.029437, 51.999992, 12.0, 52.0]" // 10 coordinates, 5 points
```
while the returned array (the result of the function) is:
```kotlin
"[Point(0.0, 40.0), Point(0.0, 44.97056)]" // 2 points
```
3 pairs of coordinates therefore seem to be "lost in translation".

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-592">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
