### ISSUE TITLE
Skiko failed to render a frame on Windows Direct3D Intel(R) HD Graphics 4600

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#601]
https://youtrack.jetbrains.com/issue/FL-14786/Blank-Window-on-User-Agreement

**Comment by SergeevPavel** [comment]
related compose issue: https://github.com/JetBrains/compose-jb/issues/1771
As it pointed there, some Intel videocards doesn't support Direct3D 12.
I see two options here, we could try to check Direct3D 12 support programmatically, or just put the videocards into black list.
@igordmn what do you think?

**Comment by igordmn** [comment]
> just put the videocards into black list

If we get the list from the official source (the intel site), it is fine as a fast fix, but it would be better to fix this issue the right way. 

As far as I remember, the check for Direct3D happens [here](https://github.com/JetBrains/skiko/blob/master/skiko/src/awtMain/cpp/windows/directXRedrawer.cc#L264). It seems it ether is not full or right, or we have bugs in drivers (in this case only the blacklist will help).

**Comment by SergeevPavel** [comment]
should be fixed after https://github.com/JetBrains/skiko/pull/603

**Comment by mahozad** [comment]
I have Intel HD Graphics 4600 and the issue resolved for me in v1.2.1.

The app prints `Failed to create DirectX12 device.` at std out at startup.  
Could you please log the fallback render API as well? I think it should probably be logged somewhere [here](https://github.com/JetBrains/skiko/blob/5616a1b18824a3aca6df7af17c5a409ad5bdfcde/skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt#L278).

Also, I think these issues are related:
  - https://github.com/JetBrains/compose-jb/issues/610#issuecomment-829075382
  - https://github.com/JetBrains/compose-jb/issues/449
  - https://github.com/JetBrains/compose-jb/issues/1771
  - https://github.com/JetBrains/skiko/issues/601

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-601">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
