### ISSUE TITLE
Android: No implementation found for void org.jetbrains.skia.paragraph.ParagraphStyleKt._nSetFontRastrSettings(long, int, int, boolean)

### ISSUE THREAD

**Issue by Octoate** [JetBrains/skiko#606]
Hi,
I am trying to disable subpixel rendering for a paragraph via a paragraph style in Skiko v0.7.36 with the following lines:

```
val paragraphStyle = ParagraphStyle()
paragraphStyle.alignment = SkiaTextUtilities.getHorizontalSkiaAlignment(primitive.text.alignment)
paragraphStyle.direction = Direction.LTR
paragraphStyle.height = paragraphHeight.toFloat()
paragraphStyle.fontRastrSettings = FontRastrSettings(FontEdging.ALIAS, FontHinting.FULL, false)
```

It works on Linux and Windows without a problem, however, it does not work on Android and crashes with the following message:

```
java.lang.UnsatisfiedLinkError: No implementation found for void org.jetbrains.skia.paragraph.ParagraphStyleKt._nSetFontRastrSettings(long, int, int, boolean) (tried Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings and Java_org_jetbrains_skia_paragraph_ParagraphStyleKt__1nSetFontRastrSettings__JIIZ)
```

Can you please have a look at it and fix this problem with the Android version? Is there a workaround for it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-606">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
