### ISSUE TITLE
Support Windows ARM64

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/skiko#607]
And publish relevant artifacts, including `org.jetbrains.skiko:skiko-awt-runtime-windows-arm64`

**Comment by VladRassokhin** [comment]
Looks like we've to first wait for https://github.com/gradle/gradle/issues/21703 and https://github.com/gradle/native-platform/pull/318

**Comment by igordmn** [comment]
> Looks like we've to first wait for https://github.com/gradle/gradle/issues/21703 and https://github.com/gradle/native-platform/pull/318

We need [this feature](https://github.com/gradle/gradle/pull/21780), but until it is implemented we can use a simple workaround - just replace "x86" by "arm64" in paths when we build for ARM64.

ARM64 support is implemented and checked. It will be merged soon after the review.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-607">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
