### ISSUE TITLE
Support Kotlin/Native on Windows(x86_64) and Linux(x86_64)

### ISSUE THREAD

**Issue by Danielku15** [JetBrains/skiko#611]
I am currently looking for a library which I could use to use Skia in my Kotlin Multiplatform library project and Skiko seems to be a very good foundation. 

Unfortunately the two platforms...

1. Kotlin/Native on Windows(x86_64)
2. Kotlin/Native on Linux(x86_64)

...are not yet in the officially supported list. Is there any special reason behind this? Considering that the Skia native libs should be there from the Kotlin/JVM targets providing a Kotlin/Native flavor for Desktop platforms should be quite feasible. 

I am aiming to target iOS ultimately, but to develop and test the Native flavor of my library desktop OS support would be great to have.

**Comment by Syrou** [comment]
Please look into mingwx64 support

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-611">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
