### ISSUE TITLE
SkiaLayer.awt.kt: no pointer events if SkikoView was set via common property instead of AWT specific method addView()

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/skiko#614]
I'm working on a common library and it would be great to be able to configure common logic (model mapping and user input mapping) in a common code, but because of this issue I have to have different init code on each platform.

Code snippet:
```
class SkiaWidget(
    private val content: Content,
    val nativeLayer: SkiaLayer
) {
    init {
        val drawable = toDrawable(content)
        val view = object : SkikoView {
            override fun onRender(canvas: Canvas, width: Int, height: Int, nanoTime: Long) {
                canvas.drawDrawable(drawable)
            }
        }
        nativeLayer.skikoView = view // no pointer events in AWT
        // nativeLayer.addView(view) //  working pointer events in AWT, but isn't common

        override fun onPointerEvent(event: SkikoPointerEvent) {
                mouseEventHandler(event.toMouseEvent(), event.platform)
            }
        }
```

Also there is no `removeMouseListener` in `addView()`, so calling it n times will cause `onPointerEvent` to be fired n times on a single event:
https://github.com/JetBrains/skiko/blob/master/skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt#L198

**Comment by IKupriyanov-HORIS** [comment]
Obsolete since [0.8.0](https://github.com/JetBrains/skiko/releases/tag/v0.8.0)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-614">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
