### ISSUE TITLE
ColorFilter seems not to work correctly (grayscale image)

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#625]
I want to create a gray scale image that's the same as created with OpenCV, but it differs.

This way I do it in OpenCV:
```
fun main() {

    OpenCV.loadLocally()

    val image = Imgcodecs.imread("photo_1.jpg")

    val targetImage = Mat(image.height(), image.width(), image.type())

    Imgproc.cvtColor(image, targetImage, Imgproc.COLOR_RGB2GRAY)

    Imgcodecs.imwrite("photo_1_opencv.png", targetImage)
}
```

And this is the way I do it in SKIA:
```
fun main() {

    val file = "photo_1.jpg"

    val image = Image.makeFromEncoded(File(file).readBytes())

    val surface = Surface.makeRasterN32Premul(image.width, image.height)

    surface.canvas.drawImageRect(
        image,
        Rect(0f, 0f, image.width.toFloat(), image.height.toFloat()),
        Paint().apply {
            colorFilter = ColorFilter.makeMatrix(
                ColorMatrix(
                    0.299000F, 0.587000F, 0.114000F, 0F, 0F,
                    0.299000F, 0.587000F, 0.114000F, 0F, 0F,
                    0.299000F, 0.587000F, 0.114000F, 0F, 0F,
                    0F, 0F, 0F, 1F, 0F
                )
            )
        }
    )

    val newImage = surface.makeImageSnapshot()

    File("photo_1_skia.png").writeBytes(
        newImage.encodeToData()!!.bytes
    )
}
```

According to https://docs.opencv.org/4.x/de/d25/imgproc_color_conversions.html this should be the right color matrix.

But the result differs. The SKIA version is a bit brighter. I want it to have the same pixel values.

If I comment out the lines with `Imgproc.cvtColor` and `colorFilter = ColorFilter.makeMatrix` in the sample above the resulting PNG has identical pixel values.

Are we sure that the color filter works correctly?
What's the proper way to grayscale an image?

Original:
![photo_1](https://user-images.githubusercontent.com/9299303/204998491-928f9054-b7b9-4039-9418-e4afb2fbfcfc.jpg)

OpenCV version:
![photo_1_opencv](https://user-images.githubusercontent.com/9299303/204998071-f9759b2b-a737-4688-b717-bcf615f979bc.png)

SKIA version:
![photo_1_skia](https://user-images.githubusercontent.com/9299303/204998187-beeda57b-13bf-4298-a2cc-d922b7a904b8.png)

**Comment by pjBooms** [comment]
It seems it does not relate to Skiko but to [Skia](https://github.com/google/skia). You'd better to open a similar issue [here](https://bugs.chromium.org/p/skia/issues/list). Once it is fixed there it will be automatically fixed for Skiko.

**Comment by StefanOltmann** [comment]
Thank you.

I reported it to https://bugs.chromium.org/p/skia/issues/detail?id=13956

**Comment by StefanOltmann** [comment]
Update: User error, SKIA is fine.

`Imgproc.COLOR_RGB2GRAY` must be changed to `Imgproc.COLOR_GRB2GRAY` because OpenCV does load images in GRB instead of RGB.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-625">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
