### ISSUE TITLE
Failed to create Typeface from path

### ISSUE THREAD

**Issue by vrublevskys** [JetBrains/skiko#635]
Hi! I have the folowwing project structure:
```
project
.
├──androidApp
├──iosApp
├──shared
│   └──src
│      ├──androidMain
│      ├──iosMain
│      └──commonMain
│         ├──kotlin
│         └──resources
│            └──fonts
│               └──times_nr.ttf
```
In `commonMain` i have `interface`
```
interface Platform {
    val typeface: Typeface
}

expect fun getPlatform(): Platform
```

and it's realisation in `androidMain`
```
class AndroidPlatform : Platform {

    private val fontFile = File("fonts/times_nr.ttf")

    init {
        Log.d("logd", "isExists: ${fontFile.exists()}")
    }

    override val typeface: Typeface = Typeface.makeFromFile(fontFile.path)
}

actual fun getPlatform(): Platform = AndroidPlatform()
```

This code is getting error `Failed to create Typeface from path="/fonts/times_nr.ttf" index=0`, and I see my log `isExists: false`. I understand, that it is not correct way to access font file. But how I can to store shared font file for iOS and Android app?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-635">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
