### ISSUE TITLE
glibc 2.29 incompatibility on Linux-arm64

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/skiko#642]
Got ULE: `java.lang.UnsatisfiedLinkError: /home/builduser/.skiko/a73502ed9c70a3f2c19a467006b469b66c4d35fda4b5771b465aa55f3c416177/libskiko-linux-arm64.so: /lib/aarch64-linux-gnu/atomics/libm.so.6: version `GLIBC_2.29' not found (required by /home/builduser/.skiko/a73502ed9c70a3f2c19a467006b469b66c4d35fda4b5771b465aa55f3c416177/libskiko-linux-arm64.so)
`

OS is Ubuntu 18.04. Same goes for CentOS 7.
Please adjust build scripts/environment for further library versions.

Also related issue: https://github.com/JetBrains/compose-jb/issues/2279

**Comment by changjinzhuan** [comment]
/home/kcrx/.skiko/8e78e87c61e63b72b088d64f5b8a0f6b7e1ca20f10bdae5caeac229d204a2b96/libskiko-linux-arm64.so: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/kcrx/.skiko/8e78e87c61e63b72b088d64f5b8a0f6b7e1ca20f10bdae5caeac229d204a2b96/libskiko-linux-arm64.so)

0.7.85.4  The problem still exists ？

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-642">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
