### ISSUE TITLE
`all Tests` task fails when run on macOS from IJ

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skiko#645]
[out.txt](https://github.com/JetBrains/skiko/files/10362336/out.txt)
```
> Task :skiko:linkDebugTestLinuxX64 FAILED
e: /Users/Pavel.Sergeev/.konan/dependencies/apple-llvm-20200714-macos-x64-essentials/bin/ld.lld invocation reported errors
The /Users/Pavel.Sergeev/.konan/dependencies/apple-llvm-20200714-macos-x64-essentials/bin/ld.lld command returned non-zero exit code: 1.
output:
ld.lld: error: undefined symbol: org_jetbrains_skia_Bitmap__1nMake
>>> referenced by Bitmap.kt:43 (/Users/Pavel.Sergeev/work/skiko/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt:43)
>>>               /var/folders/q6/td08fl996jz_lsjn70_h_7m80000kt/T/konan_temp9999442473050089758/result.o:(kfun:org.jetbrains.skia.Bitmap#<init>(){})
```
~~Looks like it works before https://github.com/JetBrains/skiko/commit/4f96dccf57b538dc80e540e638ba0ad3a76022a8~~
But I don't see any related changes.

**Comment by eymar** [comment]
Hm, is linux task `linkDebugTestLinuxX64` expected to be called on macOS at all? 
Did it work for you before?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-645">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
