### ISSUE TITLE
Skiko not working for Android API under 28

### ISSUE THREAD

**Issue by francescotescari** [JetBrains/skiko#647]
The readme states that Andoird/JVM platform is supported from API 24, however it seems that Skiko cannot run on devices with API lower than 28.
The issue is with the use of [reachabilityFence](https://developer.android.com/reference/java/lang/ref/Reference#reachabilityFence(java.lang.Object)), which is available in Android only for API 28+.
The lack of the `reachabilityFence` method on Android below 28 makes Skiko crash at runtime, even with the sample app included in this repo.

**Comment by 10ydaydream** [comment]
Does the JDK8 or earlier version not support?

**Comment by Phaestion** [comment]
I'm also running into this issue. Is there a way this can be fixed for Android with an SDK check?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-647">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
