### ISSUE TITLE
Headless support

### ISSUE THREAD

**Issue by astatio** [JetBrains/skiko#648]
The title is self-explanatory. I've found no evidence that it supports it, but can it really be used in a headless environment? Thanks.

**Comment by silabpm** [comment]
You might need to install libGL to run it on headless linux

**Comment by astatio** [comment]
> You might need to install libGL to run it on headless linux

Non-sense. Have you even tried skiko in a headless environment? You'll get an error clearly indicating that it's running in a headless environment and it can't.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-648">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
