### ISSUE TITLE
Make fromInterop extension functions internal

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/skiko#663]
Currently all programs that use skiko and compose desktop have access to `fromInterop` and `fromInteropNativePointerArray` which are defined on `Any` and so are suggested on every object by the IDE as a useless clutter.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-663">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
