### ISSUE TITLE
[iOS] Battery usage and performance

### ISSUE THREAD

**Issue by chaserunner** [JetBrains/skiko#671]
Hi. Sample app is consuming a lot of resources despite being pretty basic example.
Both CPU and GPU are consuming a lot of resources, and battery is draining.
<img width="1074" alt="Screenshot 2023-02-15 at 18 37 36" src="https://user-images.githubusercontent.com/3989307/222715001-6d3a86f7-fdc5-4f94-a250-0aed154cb9cb.png">

What can be done in order to optimise the performance especially if canvas is static and isn't updating every frame? Plus if only part of canvas should be updated or simple translation should be applied to already rendered canvas, is there a way to prevent each frame from re-rendering?

**Comment by dima-avdeev-jb** [comment]
Thanks, we will try to do it better!

**Comment by dima-avdeev-jb** [comment]
Soon we will make some changes in iOS rendering. I think it will increase performance https://github.com/JetBrains/skiko/pull/668

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-671">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
