### ISSUE TITLE
Update Matrix implementation

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/skiko#673]
- Implement missing methods in [`Matrix44`](https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Matrix44.kt) class to match [`SkM44`](https://github.com/google/skia/blob/main/include/core/SkM44.h) from skia;
- Make default constructor instead of storing mutable `IDENTITY` object (applied to `Matrix33` too);

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-673">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
