### ISSUE TITLE
implement ClipboardManager_getText for js

### ISSUE THREAD

**Issue by julianhille** [JetBrains/skiko#676]
Currently getting text from the clipboard is not implemented in js.

navigator.clipboard.getText is async might be the root cause why it is not implemented until now.

**Comment by julianhille** [comment]
Wouldn't it be feasible to just return in the Javascript case a promise and the jsmain impl on the client then needs to take care of awaiting it?

Just thinking loud. This sounds doable but kinda ugly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-676">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
