### ISSUE TITLE
Enable screenshots tests on macOS

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#678]
They were disabled [here](https://github.com/JetBrains/skiko/pull/472) because of the difference in color correction across different devices and versions.

It is not good that we don't run tests for macOS on CI. We need to find a way to make screenshots without color correction

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-678">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
