### ISSUE TITLE
Refactor SkikoPointerEvent API

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#680]
![image](https://user-images.githubusercontent.com/5963351/227448136-c45978e0-cffe-4734-b9c1-ff95ba52f47a.png)

1. Decide should we pass `x`/`y` in pixels instead of points. This is the behaviour of Android and Compose, but not of UIKit or Swing
2. Rename `deltaX`/`deltaY` to scrollDeltaX/scrollDeltaY
3. Rename `timestamp` to `timeMillis`
4. Rename `platform` to `platformEvent` (it can be misinterpreted as `Platform` type which is not true).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-680">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
