### ISSUE TITLE
Follow XDG Base Directory

### ISSUE THREAD

**Issue by suwermave** [JetBrains/skiko#707]
XDG Base Directory specification defines where these files should be looked for by defining one or more base directories relative to which files should be located.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

As for now, applications that use skiko as dependency create .skiko folder in user $HOME directory.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-707">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
