### ISSUE TITLE
Support for browser window resizing

### ISSUE THREAD

**Issue by Ic-ks** [JetBrains/skiko#722]
At the moment it is only possible to resize the compose content of a browser window by using workarounds. There is a whole discussion about the resizing problem and its workaround: https://slack-chats.kotlinlang.org/t/2224952/compose-for-web-on-canvas-skia-wasm-i-have-a-simple-function 
This workaround uses the internal skiko API and is not very fast: it calls `ComposeWindow.layer.layer.attachTo(canvas)` for each window resizing event which creates a new `CanvasRenderer`. Is there a reason why there is no official support for resizing the `ComposeWindow` if the browser window is resized? If not, would it be possible to provide it :) ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-722">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
