### ISSUE TITLE
Fix variable font conversion from AWT to Skiko

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#726]
See this comment https://github.com/JetBrains/skiko/pull/639#discussion_r1233409542

some font families in 2 tests were inored:
```
should be able to convert all default AWT fonts
should provide all the system fonts also available via AWT
```

After fixing the issue we should remove ignoredFamilies

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-726">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
