### ISSUE TITLE
Apple Silicon M1 Arm64

### ISSUE THREAD

**Issue by abueide** [JetBrains/skiko#74]
Is desktop compose/skiko supported for apple's m1 silicon or other arm64 devices?

**Comment by olonho** [comment]
Yes, it is.

**Comment by abueide** [comment]
My bad, it seems to work fine now. It was probably an unrelated issue with my gradle setup, or it might have had to do with jcenter having an outage yesterday. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-74">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
