### ISSUE TITLE
Support decoding Image from a streaming data source

### ISSUE THREAD

**Issue by colinrtwhite** [JetBrains/skiko#741]
Hi, I was wondering if it's possible to support streaming image data when decoding an `Image`. At the moment it looks like `Image` only has methods to decode the image when its data is already all in memory (e.g. `ByteArray`, `Pixmap`). This requires consumers to buffer the entire image data into memory before decoding, which isn't ideal for performance.

I'd be nice to support an `InputStream`-like primitive (can be a custom type) so that users can decode `Image`s without totally reading them into memory first. This would be especially useful for decoding from `File`s.

It looks [Skia already has support](https://android.googlesource.com/platform/external/skia/+/eclair-release/include/images/SkImageDecoder.h#147) for streams that could hopefully be leveraged. Thanks for the great library!

**Comment by VDostoyevskiy** [comment]
I guess this will land with [kotlinx-io](https://github.com/Kotlin/kotlinx-io) support as base or extensions?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-741">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
