### ISSUE TITLE
Support web events on mobile devices

### ISSUE THREAD

**Issue by jershell** [JetBrains/skiko#747]
On mobile devices scroll, drag&drop, not working.
I think its related to this part https://github.com/JetBrains/skiko/blob/f44fd6c4ca163bdac83469266dc3d8311a014440/skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt#L108

The pointer events haven't a listener
I not sure, maybe if we will do proxy the `pointer*` events to scene it should enough to support.

https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/pointermove_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerup_event

**Comment by jershell** [comment]
fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-747">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
