### ISSUE TITLE
macOs. Wrong colors on Metal

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#75]
Example:

```
canvas.drawRect(Rect.makeXYWH(0f, 0f, 100f, 100f), Paint().apply {
    mode = PaintMode.FILL
    color = Color.makeARGB(0, 255, 0, 0)
})
canvas.drawRect(Rect.makeXYWH(100f, 0f, 100f, 100f), Paint().apply {
    mode = PaintMode.FILL
    color = Color.makeARGB(63, 255, 0, 0)
})
canvas.drawRect(Rect.makeXYWH(200f, 0f, 100f, 100f), Paint().apply {
    mode = PaintMode.FILL
    color = Color.makeARGB(127, 255, 0, 0)
})
canvas.drawRect(Rect.makeXYWH(300f, 0f, 100f, 100f), Paint().apply {
    mode = PaintMode.FILL
    color = Color.makeARGB(191, 255, 0, 0)
})
canvas.drawRect(Rect.makeXYWH(400f, 0f, 100f, 100f), Paint().apply {
    mode = PaintMode.FILL
    color = Color.makeARGB(255, 255, 0, 0)
})
```
OpenGL:
![Screenshot 2021-03-17 at 11 48 28](https://user-images.githubusercontent.com/5963351/111441206-2a164700-8718-11eb-8216-eaad0ad0b3ba.png)

Metal:
![Screenshot 2021-03-17 at 11 50 04](https://user-images.githubusercontent.com/5963351/111441221-2da9ce00-8718-11eb-99f9-a75d8844e028.png)

**Comment by igordmn** [comment]
It seems we had wrong colors on OpenGL.

MacOs corrects all colors by system color profile in all native applications.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-75">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
