### ISSUE TITLE
Permit creating arbitrary color spaces

### ISSUE THREAD

**Issue by LoadingByte** [JetBrains/skiko#768]
First of all, I'd like to thank you for this amazing binding! Once you run into the severe limitations of Java2D on the JVM platform (e.g., rendering being limited to 8-bit sRGB), migrating Skia is a nice way to overcome these restrictions, and Skiko makes it extremely easy to use.

At the moment, Skiko's `ColorSpace` class is unfortunately limited to sRGB, linear sRGB, and Display P3. Fortunately, Skia offers the convenient factory [`SkColorSpace::MakeRGB`](https://skia.googlesource.com/skia/+/refs/heads/main/include/core/SkColorSpace.h#122) for creating arbitrary color spaces. Wrapping this function in Skiko would in turn require to represent the structs [`skcms_Matrix3x3`](https://skia.googlesource.com/skia/+/refs/heads/main/modules/skcms/skcms.h#26) (which could be done by repurposing `Matrix33`) and [`skcms_TransferFunction`](https://skia.googlesource.com/skia/+/refs/heads/main/modules/skcms/skcms.h#46) in Kotlin. As part of this, exposing the constants in the [`SkNamedGamut`](https://skia.googlesource.com/skia/+/refs/heads/main/include/core/SkColorSpace.h#65) and [`SkNamedTransferFn`](https://skia.googlesource.com/skia/+/refs/heads/main/include/core/SkColorSpace.h#42) namespaces would massively improve usability of the new factory.

As far as I can tell, setting up a dev environment for Skiko is quite complicated. Nevertheless, I'd be happy to contribute a pull request if you don't have the resources to add the above-mentioned factory yourself, but someone else would probably need to quickly test it prior to merging.

**Comment by pjBooms** [comment]
>Nevertheless, I'd be happy to contribute a pull request

It would be great. Don't forget to include tests to PR to make it easier to review

**Comment by LoadingByte** [comment]
Alright, I'll work on this.

**Comment by igordmn** [comment]
> [skcms_Matrix3x3](https://skia.googlesource.com/skia/+/refs/heads/main/modules/skcms/skcms.h#26) (which could be done by repurposing Matrix33) and [skcms_TransferFunction](https://skia.googlesource.com/skia/+/refs/heads/main/modules/skcms/skcms.h#46)

Prefereable to reuse existing `Matrix33` (and implement `TransferFunction` in Kotlin-only code). The current Skiko strategy - implement data structures in Kotlin and pass them as primitives to the native world (example - `Canvas.setMatrix`)

**Comment by LoadingByte** [comment]
After reading through some Skiko code to find out how you're doing things, this is exactly what I've decided on; thanks for the hint nonetheless!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-768">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
