### ISSUE TITLE
Metal. Get rid of the white bars when we resize a window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#77]
https://user-images.githubusercontent.com/5963351/111454654-ee827980-8725-11eb-8109-d8c855aa41d6.mov

Probably it is because we don't render in AppKit thread now. We render in Swing thread, so the actual drawing after resize can be delayed.

**Comment by tonsky** [comment]
The only thing that worked for us in https://github.com/jetbrains/jwm:

- Use `CAMetalLayer`, not `MtkView`
- Set `displaySyncEnabled = NO`
- Use vsync signal from `CVDisplayLink`
- Set `presentsWithTransaction = YES`
- Use `waitUntilScheduled` before present

Take a look here https://github.com/JetBrains/JWM/blob/661e24116757c6f0c85d401e0a0378ecf7ead360/macos/cc/LayerMetal.mm

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-77">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
