### ISSUE TITLE
ResourceProvider for Skottie AnimationBuilder requested

### ISSUE THREAD

**Issue by netherpyro** [JetBrains/skiko#778]
For Skija, there is a ResourceProvider to load image assets for Lottie animation.
Since Skiko's Skottie won't render base64 images, there is a request for implementing this feature.
Are there any plans to at least make base64 images work in Skottie?

Here is related resolved issue from Skija: https://github.com/JetBrains/skija/issues/129

**Comment by dima-avdeev-jb** [comment]
For now we don't plan to support base64 in Skiko.

**Comment by netherpyro** [comment]
Got it, so what about Resource Provider for Animation Builder, is there a chance to see this option in the upcoming versions? Thanks

**Comment by dima-avdeev-jb** [comment]
> what about Resource Provider for Animation Builder, is there a chance to see this option in the upcoming versions?

Sorry, but for now we have different priority tasks

**Comment by ismai117** [comment]
Can you point me to resources that can help me implement a workaround for rendering base64 images for Skottie animations?
