### ISSUE TITLE
Skiko is still using Kotlin 1.8.20

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/skiko#791]
See https://github.com/JetBrains/skiko/blob/master/skiko/build.gradle.kts#L11

Can this be upgraded to 1.9.0 to match the latest in compose-multiplatform 1.5.0 beta 2?

**Comment by kirill-grouchnikov** [comment]
Also coroutines dependency is 1.5.2 while the latest is 1.7.3

**Comment by dima-avdeev-jb** [comment]
This is because we want to support usage of older Kotlin versions (like 1.8.21) with Compose 1.5.0 as well.

Probably, we could update Kotlin version in Skiko after release of Compose 1.5.0

@kirill-grouchnikov 
Why do you need Kotlin 1.9.0 in Skiko?

**Comment by pkulikowski** [comment]
One example from my side for wanting Kotlin 1.9.+ is that it is required in order to use XCode 15.

**Comment by dima-avdeev-jb** [comment]
Yes, Xcode15 works better with Kotlin 1.9.10
But there are workaround described here:
https://youtrack.jetbrains.com/issue/KT-60230

**Comment by dima-avdeev-jb** [comment]
@chaserunner 
> Skiko is very hard to combine with other libraries we use, coroutines as an example.

Is it related with Kotlin version ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-791">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
