### ISSUE TITLE
AWT & WindowsOpenGLRedrawer occasionally causes heavy UI lag

### ISSUE THREAD

**Issue by serivesmejia** [JetBrains/skiko#792]
I'm using Skiko to simulate code that utilizes the android.graphics package and draws it onto a Swing JFrame (from which I unfortunately cannot get rid of, since the base application was written as such). 

The issue is, firsts of all, Skiko isn't able to use the DirectX12 adapter for unknown reasons, even though dxdiag specifies my computer supports it;

![image](https://github.com/JetBrains/skiko/assets/20974568/9cd4133f-5f77-4d7e-8478-129350aeb85d)
![image](https://github.com/JetBrains/skiko/assets/20974568/74bdccb2-deed-48e5-997c-8a9fefaadac7)

So, it falls back to OpenGL, which works fine most of the time, but in certain times it will ocassionally cause the whole UI to heavily lag. Buttons and rendering become extemely unresponsive (up to 5 seconds to react), meanwhile the main thread does its job just fine, which somewhat tells me that it might not be an issue with my code.

Taking a look at a java profiler, it seems like some sort of call to glFinish is taking a loooong time; 

![image](https://github.com/JetBrains/skiko/assets/20974568/4ed8c669-af33-41ff-81b8-5d254707396a)

From this, we can also see that my rendering code is not really the culprit of this issue;

![image](https://github.com/JetBrains/skiko/assets/20974568/f021007f-870e-4055-b245-24292e138626)

I don't really have a clue on what could be causing this issue, so any help would be appreciated greatly.
I have tested with a minimal Swing app with just the canvas with a blue background and something similar seems to happen. If you need more information I'll be happy to provide it.
Thank you in advance!

**Comment by mazunin-v-jb** [comment]
Hello! Thanks for submitting the issue.
I'll pass it on to the team.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-792">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
