### ISSUE TITLE
Any plans to add SkImage::MakeFromTexture support?

### ISSUE THREAD

**Issue by hellozyemlya** [JetBrains/skiko#795]
I am trying to utilize skiko inside game engine, and I want to use some textures from OpenGL and lack of this method. Any plans to add it in future?

**Comment by elijah-semyonov** [comment]
No plans currently, but you can add one by yourself! :)

You'll need to update those files and build skiko locally (see RELEASE.MD):
https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Image.kt
https://github.com/JetBrains/skiko/blob/master/skiko/src/nativeJsMain/cpp/Image.cc

**Comment by mandarin6b0** [comment]
@hellozyemlya did you managed to achieve this? :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-795">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
