### ISSUE TITLE
Is there a way to generate cmake or other kind of project for native code?

### ISSUE THREAD

**Issue by hellozyemlya** [JetBrains/skiko#796]
For convenience purposes I want to get some kind of project for native code, to ensure it can be opened in clion, so it will be possible to get proper syntax highlight and code completion for c++ code. Is it possible now?

**Comment by hellozyemlya** [comment]
Found out there is file after native build - build/tmp/compileJvmBindingsMacosArm64/common-args.txt, created simple python script that setups vs code c++ extension and makes it easy to change and extend code:
```python
import json

args_file_path = "skiko/build/tmp/compileJvmBindingsMacosArm64/common-args.txt"
vscode_cpp_settings = ".vscode/c_cpp_properties.json"

INCLUDE = []
DEFINE = []

lines = iter(open(args_file_path, "r").readlines())


def next_arg() -> str:
    return next(lines).strip()


try:
    while True:
        cur_argument = next_arg()
        if cur_argument == "-I":
            INCLUDE.append(next_arg())
            continue
        if cur_argument.startswith("-D"):
            DEFINE.append(cur_argument[2:])
except StopIteration:
    pass

print(INCLUDE)
print(DEFINE)

config = json.load(open(vscode_cpp_settings, "r"))

config["configurations"][0]["includePath"] = INCLUDE
config["configurations"][0]["defines"] = DEFINE

json.dump(config, open(vscode_cpp_settings, "w"), indent=2)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-796">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
