### ISSUE TITLE
Provide access to SkPathUtils

### ISSUE THREAD

**Issue by MaxNagl** [JetBrains/skiko#797]
In Version 0.7.77 `Paint.getFillPath()` was removed.

In the release notes for skia Milestone 110  it sais:

> SkPaint::getFillPath has been replaced with skpathutils::FillPathWithPaint from include/core/SkPathUtils.h. The functionality should be the same.

Please provide access to SkPathUtils.

**Comment by SergeevPavel** [comment]
@morrisseyai it would be great to bring it back? Could you send a PR?
If there are some API that stable in skia and not covered by skiko bindings we will be happy to merge it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-797">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
