### ISSUE TITLE
Missing API `setColor`

### ISSUE THREAD

**Issue by iAkariAk** [JetBrains/skiko#807]
Hi, In `org.jetbrains.skia.Bitmap` there is `fun getColor(x: Int, y: Int): Int` but there is no `fun setColor(x: Int, y: Int, color: Int)`
I hope to be able to supplement this API

**Comment by eymar** [comment]
Hi!
SkBitmap (in Skia) doesn't have `setColor` method and therefore skiko doesn't have it too.

Maybe setPixelRef or setPixels do what you need: https://api.skia.org/classSkBitmap.html#ae255f6121d2c030fa49b70b9055ad54f

In skiko: https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt#L679

Or maybe SkBitmap.erase method is what you need: https://api.skia.org/classSkBitmap.html#aa57dae30c3cb228284c921102ce895ce

https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt#L780

**Comment by iAkariAk** [comment]
> 你好！ SkBitmap（在Skia中）没有`setColor`方法，因此skiko也没有它。
> 
> 也许 setPixelRef 或 setPixels 可以满足您的需要：https://api.skia.org/classSkBitmap.html#ae255f6121d2c030fa49b70b9055ad54f
> 
> 在skiko中：https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt#L679
> 
> 或者也许 SkBitmap.erase 方法就是您所需要的：https://api.skia.org/classSkBitmap.html#aa57dae30c3cb228284c921102ce895ce
> 
> https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt#L780

Thank you so much!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-807">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
