### ISSUE TITLE
Can skiko support impeller?

### ISSUE THREAD

**Issue by liuqingdada** [JetBrains/skiko#819]

**Comment by eymar** [comment]
As Kirill already answered, Skiko will keep using Skia.
As for Compose, the answer is here - https://github.com/JetBrains/compose-multiplatform/issues/3886 :)

**Comment by liuqingdada** [comment]
@kirill-grouchnikov @eymar Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-819">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
