### ISSUE TITLE
Path.convertConicToQuads() incorrectly implemented

### ISSUE THREAD

**Issue by romainguy** [JetBrains/skiko#820]
`Path.convertConicToQuads()` invokes `SkPath::ConvertConicToQuads` via `_nConvertConicToQuads()` but misuses the return value. Here is the current implementation:

```
        fun convertConicToQuads(p0: Point, p1: Point, p2: Point, w: Float, pow2: Int): Array<Point> {
            Stats.onNativeCall()
            val maxResultPointCount = (1 + 2 * (1 shl pow2)) // See Skia docs
            var pointCount = 0
            val coords = withResult(FloatArray(maxResultPointCount * 2)) {
                pointCount = _nConvertConicToQuads(p0.x, p0.y, p1.x, p1.y, p2.x, p2.y, w, pow2, it)
            }
            return Array(pointCount) { Point(coords[2 * it], coords[2 * it + 1]) }
        }
```

The value returned by `_nConvertConicToQuads` is used as a number of points when it's actually a number of *quadratic curves*. Since each curve is made of 3 points (although in the array the curves all overlap by 1 point), the returned array is missing most of the data, and provides invalid results (returning for instance 2 points when at least 3 are required to build a single quadratic curve).

**Comment by LouisCAD** [comment]
Is that `convertConicToQuads` function used somewhere in Compose Multiplatform?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-820">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
