### ISSUE TITLE
Attach Skikoview to Compose Web

### ISSUE THREAD

**Issue by dbof10** [JetBrains/skiko#825]
For desktop, I use such snippet to wrap `GenericSkikoView` to convert it to a Composable Component . 

```
@Composable
actual fun ComposeChartView(modifier: Modifier) {


    SwingPanel(factory = {

        JPanel().apply {
            layout = BoxLayout(this, Y_AXIS)

            val skiaLayer = SkiaLayer()
            skiaLayer.addView(GenericSkikoView(skiaLayer, ChartView()))

            skiaLayer.attachTo(this)
            skiaLayer.needRedraw()
        }
    }, modifier = modifier)
}
```

How do I do it for web wasm?

**Comment by pjBooms** [comment]
Duplicate to https://github.com/JetBrains/compose-multiplatform/issues/3924

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-825">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
