### ISSUE TITLE
Please enable use of FilterQuality

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#834]
I want to scale images using a higher quality than the default.

Unfortunately this API is not exposed:
```
val paint = Paint().apply {
    filterQuality = FilterQuality.HIGH
}
```

Please make it available.

**Comment by mazunin-v-jb** [comment]
Thanks! We will take a look.

**Comment by igordmn** [comment]
`FilterQuality` only exists in Android, Compose API and the old Skia API.

The new Skia has [`canvas.drawImageRect(samplingMode = )`](https://github.com/JetBrains/compose-multiplatform-core/blob/010a7395dd460890bb5bb23df812e323988adca8/compose/ui/ui-graphics/src/skikoMain/kotlin/androidx/compose/ui/graphics/SkiaBackedCanvas.skiko.kt#L232), which is a replacement of the old `paint.filterQuality`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-834">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
