### ISSUE TITLE
Crashing compose app on OpenJDK 17-ea+15

### ISSUE THREAD

**Issue by tonsky** [JetBrains/skiko#84]
Originally reported at https://github.com/JetBrains/skija/issues/102

I looked into it briefly, looks like someone tries to close Surface or BackendRenderTarget which has already been closed. Skija fails during the check for double close, but that only masks the issue.

Also, you don’t need to close and recreate BackendRenderTarget/Surface on each frame (skiko example does that). Only on resize

**Comment by tonsky** [comment]
cc @sureshg

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-84">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
