### ISSUE TITLE
Bad compression ratio for PNG images

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/skiko#847]
Skia can encode images into a ByteArray. I noticed however that doing that for PNG images results in much larger images than usual. Something seems to be wrong with the compression. Attached please find a full project to reproduce this issue. The original image is already a PNG with a size of 870_254 bytes. After reading that in and storing again as PNG image its size becomes a whopping 1_291_525 bytes. There must be something wrong with the compression or its settings. Playing with the quality setting only makes things even worse.

Tested on
macOS Sonoma 14.1.2
kotlin.version=1.9.21
agp.version=8.1.4
compose.version=1.6.0-dev1334

[PNGSizeDemo.zip](https://github.com/JetBrains/skiko/files/13684004/PNGSizeDemo.zip)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-847">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
