### ISSUE TITLE
Support inSampleSize and decoding region like Android's BitmapFactory and BitmapRegionDecoder

### ISSUE THREAD

**Issue by panpf** [JetBrains/skiko#853]
I am developing image loading framework and image scaling components for kotlin multiplatform. I need a cross-platform image decoding library that supports decoding region and downsampling, similar to the functions of BitmapFactory and BitmapRegionDecoder in Android. Skiko's Image currently only supports full decoding of images. 

Are there any plans to provide decoding region and downsampling support?

**Comment by eymar** [comment]
Do you know if there is such a feature in skia?

Since skiko is a kotlin wrapper  for skia, it provides a subset of APIs available in skia.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-853">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
