### ISSUE TITLE
Strange repainting problem

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/skiko#855]
For some reason Skiko may not repaint content. In my case it happens when I debounce resize events.  The most strange thing is that adding an invisible Compose Canvas in a composition fixes this issue.

https://github.com/JetBrains/skiko/assets/14200189/bf2664e5-e4e3-4e93-bb28-8e0a9a4eae50

We faced with this issue in the [lets-plot-skia](https://github.com/JetBrains/lets-plot-skia/) project.   

I made a minimal repro and readme with images and video:  
https://github.com/IKupriyanov-HORIS/skiko-repaint-issue/

I think this worked with Compose <= 1.4.0 so may be it caused by changes in Compose.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-855">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
