### ISSUE TITLE
Add binding for SkCodec::getScaledDimensions()

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#861]
I want a fast & memory efficient way to downsample an JPG to a thumbnail.

The basic code to do so looks like this:
```
        val data = Data.makeFromBytes(bytes)

        val codec = Codec.makeFromData(data)

        val imageInfo = ImageInfo(
            width = codec.width / 2,
            height = codec.height / 2,
            colorType = codec.colorType,
            alphaType = codec.alphaType
        )

        val bitmap = Bitmap()
        bitmap.setImageInfo(imageInfo)
        bitmap.allocPixels()
```

But for a lot of images this does not work as it results in invalid dimensions.

That's why `SkCodec::getScaledDimensions()` exists.

See here:
https://chromium.googlesource.com/skia/+/refs/heads/main/include/codec/SkCodec.h#252

Here is the implementation for JPEG:
https://chromium.googlesource.com/skia/+/refs/heads/main/src/codec/SkJpegCodec.cpp#407

It forwards this request to libjpeg, because calculating valid dimensions seems to involve some magic:
https://chromium.googlesource.com/skia/+/refs/heads/main/src/codec/SkJpegCodec.cpp#397

**Comment by saket** [comment]
@StefanOltmann Do you know if [telephoto](https://github.com/saket/telephoto/issues/9) can benefit from this for decoding bitmap regions in common code?

**Comment by StefanOltmann** [comment]
@saket I would assume that it would, but I'm not sure. Downsampling gives faster access to scaled down versions of an JPG.

**Comment by colinrtwhite** [comment]
I think [Coil](https://github.com/coil-kt/coil) could also benefit this as well. Currently on non-Android platforms we decode the image at full size then redraw it at a smaller size (if necessary).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-861">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
