### ISSUE TITLE
Support for Linux DRM

### ISSUE THREAD

**Issue by FlysoftBeta** [JetBrains/skiko#863]
Hi, I want to use skiko on Linux devices (like Raspberry Pi) directly and without any window managers.

Implementation reference: https://github.com/slint-ui/slint/tree/master/internal/backends/linuxkms

I can create a PR for this if possible.

**Comment by frankkienl** [comment]
See:
https://github.com/JakeWharton/composeui-lightswitch

See also:
https://github.com/JetBrains/skiko/issues/918

**Comment by FlysoftBeta** [comment]
> JakeWharton got DRM working, see: https://github.com/JakeWharton/composeui-lightswitch
> 
> See also: #918

That's epic! so freaking interesting

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-863">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
