### ISSUE TITLE
Application crashing when invoking skiko

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/skiko#876]
On a linux amd64 computer, my desktop application utilizing compose desktop 1.6.0-dev1369 is crashing due to an error in the JRE:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9bda509a8b, pid=2063776, tid=2063945
#
# JRE version: OpenJDK Runtime Environment (17.0.9) (build 17.0.9+0-17.0.9b1087.11-11362436)
# Java VM: OpenJDK 64-Bit Server VM (17.0.9+0-17.0.9b1087.11-11362436, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libskiko-linux-x64.so+0x109a8b]  Java_org_jetbrains_skiko_swing_LinuxOpenGLSwingRedrawer_makeOffScreenBuffer+0x3b
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

The full log can be found here:
[hs_err_pid2089337.log](https://github.com/JetBrains/skiko/files/14380642/hs_err_pid2089337.log)

I have tried skiko version 0.7.85.4 and 0.7.90 and both have caused this error.

**Comment by jimgoog** [comment]
The crash takes down the entire AndroidStudio JVM.  Interestingly, the crash appears to only occur on a Linux machine and only when an Android device is connected and running with "Device mirroring" in AndroidStudio prior to initializing the Compose view.

**Comment by dima-avdeev-jb** [comment]
Thanks for this Issue!
I will discuss it with our team

**Comment by dima-avdeev-jb** [comment]
@YasserDbeis can you please provide a minimal reproducible sample of your project?

**Comment by dima-avdeev-jb** [comment]
I was tried to reproduce this bug [with initial project](https://kmp.jetbrains.com/), Compose version 1.6.0-dev1369 on Linux Manjaro.
But din't found crash.

**Comment by YasserDbeis** [comment]
We can only reproduce, as Jim stated above, with a pre-condition of the device mirroring feature running in Android Studio. It is worth noting that the device mirroring feature utilizes ffmpeg for rendering, which can manipulate native memory and thus can be related to SIGSEGV from skia.

Here are the exact steps you can take on a linux machine to reproduce:

1. Download a canary release of Android Studio (https://developer.android.com/studio/preview)
2. Open up any android project
3. Navigate to the toolbar’s help dropdown.
4. Select “Edit Custom VM Option…”
5. In the opened `studio.vmoptions` file, on a new line add the following: `-Dprofiler.task.based.ux=true`
6. Save the changes if not auto-saved already.
7. Restart Android Studio
8. Turn on device mirroring via File > Tools > Device Mirroring > Enable the top two options (**Activate mirroring when a new physical device is connected** & **Activate mirroring when launching an app on a physical device**)
10. Enable usb debugging in develop on a physical android device (in developer options)
11. Connect the physical android device 
12. Open up the "Running devices" tool window, if the device is already mirroring, great, if not, click the plus button and select the running device.
13. Open up the profiler tool window
14. Observe crash

**Comment by igordmn** [comment]
After investigation, it appears that https://github.com/JetBrains/skiko/pull/877 is enough. As it is only Software that is available on machines where we had the crash.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-876">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
