### ISSUE TITLE
0.7.94 isn't published to Maven Central

### ISSUE THREAD

**Issue by colinrtwhite** [JetBrains/skiko#880]
Looks like `0.7.94` isn't [published](https://repo.maven.apache.org/maven2/org/jetbrains/skiko/skiko/0.7.94/skiko-0.7.94.pom) to Maven Central (only `https://maven.pkg.jetbrains.space/public/p/compose/dev`), however `0.7.93` is [published](https://repo.maven.apache.org/maven2/org/jetbrains/skiko/skiko/0.7.93/skiko-0.7.93.pom). Could you publish `0.7.94` to Maven Central? Thanks!

**Comment by colinrtwhite** [comment]
Actually looks like only [the versions](https://repo.maven.apache.org/maven2/org/jetbrains/skiko/skiko/) used by Compose Multiplatform stable are published to Maven Central. If that's intentional feel free to close!

**Comment by MatkovIvan** [comment]
> If that's intentional feel free to close!

Yep, it's how it works now. The reasoning is 0.x version of skiko

**Comment by MatkovIvan** [comment]
The versions with important bug fixes will be published to Maven Central, but now it's aligned with Compose Multiplatform

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-880">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
