### ISSUE TITLE
A method for enabling antialiasing for Text and SVGs/Images targeting both Android/iOS

### ISSUE THREAD

**Issue by akiirax** [JetBrains/skiko#884]
Hello,

What are possible ways to enable antialiasing for Text and SVGs/Images targeting both Android/iOS?

We're having a hard time finding any resources to enable that.

Any resources/pointers/PoCs would be highly appreciated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-884">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
