### ISSUE TITLE
How to use ParagraphBuilder with a Font resource resolved through Compose Multiplatform new resource loading?

### ISSUE THREAD

**Issue by akiirax** [JetBrains/skiko#886]
Hello,

How to use ParagraphBuilder with a custom Font file/resource resolved through Compose Multiplatform new resource loading?

I was told that you guys are the go-to for this @dima-avdeev-jb @DevSrSouza :)

**Comment by terrakok** [comment]
Could you explain the case and share an example of source code how you want to use the resources librar?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-886">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
