### ISSUE TITLE
Setting anti alias has no effect

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#896]
I wanted to improve the quality of scaled down images and tried setting `isAntiAlias`, but I found out that for all sampling modes it does not have any effect. If the image is saved to PNG bytes there are byte identical regardless of this setting.

```
fun Image.scaleToThumb(): Image {

    val surface = Surface.makeRasterN32Premul(480, 320)

    surface.canvas.drawImageRect(
        image = this,
        src = Rect.makeWH(width.toFloat(), height.toFloat()),
        dst = Rect.makeWH(480f, 320f),
        samplingMode = SamplingMode.LINEAR,
        paint = Paint().apply {
            isAntiAlias = true // <-- No effect
        },
        strict = true
    )

    return surface.makeImageSnapshot()
}
```

**Comment by StefanOltmann** [comment]
Looks like anti aliasing is not expected to have an effect on the images.

https://groups.google.com/g/skia-discuss/c/_ICFWgWXT1w/m/gp0XFM5OAQAJ

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-896">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
