### ISSUE TITLE
macOS ARM64 artifact contains x64 dylib

### ISSUE THREAD

**Issue by MaximPestryakov** [JetBrains/skiko#899]
<img width="388" alt="Screenshot 2024-03-28 at 12 11 04 PM" src="https://github.com/JetBrains/skiko/assets/17238054/762e64fa-b851-40f5-8c18-23e6e4de32f9">

And because of that macOS ARM64 jar weighs twice as much as macOS x64 jar

**Comment by m-sasha** [comment]
See discussion here: https://github.com/JetBrains/compose-multiplatform/issues/3859

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-899">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
