### ISSUE TITLE
macOs. use NSWindowDidChangeOcclusionStateNotification instead of delay(500) when window isn't visible

### ISSUE THREAD

**Issue by igordmn** [JetBrains/skiko#90]
See https://github.com/JetBrains/skiko/blob/dde71c3b67f55c062a71093d82fc35df4c5e060e/skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt#L76

Currently we have small lag:

https://user-images.githubusercontent.com/5963351/113586734-85ac6400-9636-11eb-959c-850f5d4ab7cb.mov

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-90">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
