### ISSUE TITLE
Reuse existing ImageBitmap

### ISSUE THREAD

**Issue by p-lr** [JetBrains/skiko#900]
Is it possible to reuse the allocated memory of an existing `ImageBitmap` to get another `ImageBitmap`? I'm asking this for desktop or ios platforms.

For example, on Android, this is possible using the "inBitmap" parameter:
```kotlin
actual fun Source.toImage(existing: ImageBitmap?): ImageBitmap? {
    val options = BitmapFactory.Options()
    options.inScaled = false
    options.inMutable = true
    options.inBitmap = existing?.asAndroidBitmap()

    return BitmapFactory.decodeStream(this.asInputStream(), null, options)?.asImageBitmap()
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-900">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
