### ISSUE TITLE
Support Paragraph.getPath

### ISSUE THREAD

**Issue by pusolito** [JetBrains/skiko#908]
Skia supports the ability to get the Path for a line within an [SkParagraph](https://github.com/google/skia/blob/5101cbe5a6bb6f5b05c3f582202f6745f9abe58e/modules/skparagraph/include/Paragraph.h#L121). Can this functionality be ported to Skiko as well?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-908">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
