### ISSUE TITLE
Project Panama

### ISSUE THREAD

**Issue by FlysoftBeta** [JetBrains/skiko#911]
Hello. Is there any plan to migrate current JNI calls to Project Panama? This might reduce some significant overhead.

**Comment by JakeWharton** [comment]
> The Project Panama will be likely to be stabilized in JDK22.

JDK 22 released one month ago and it did stabilize Panama.

https://jdk.java.net/22/release-notes

**Comment by DRSchlaubi** [comment]
It didn't? https://openjdk.org/jeps/454
