### ISSUE TITLE
Add EGL support

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/skiko#918]
This involves at minimum two things:
* Adding `skia_use_egl=true` to the 'skia-pack' build.
* Adding a `makeEGL()` function in `DirectContext.kt`/`DirectContext.cc` by duplicating the `makeGL()` plumbing and changing it to reference `GrGLMakeEGLInterface`.

I have this working in a fork, but I'm not sure about the implications of additionally linking against EGL, if any.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-918">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
