### ISSUE TITLE
Add support for GrBackendTexture

### ISSUE THREAD

**Issue by refactorinqq** [JetBrains/skiko#919]
It would be nice if Skiko had bindings for GrBackendTexture, I use Skiko for UI in my application and I would like to import GL texture into an image and apply effects to them.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-919">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
