### ISSUE TITLE
on ios HEIC files are not supported in Image.makeFromEncoded

### ISSUE THREAD

**Issue by antailyaqwer** [JetBrains/skiko#942]
**Versions**
- Skiko: 0.8.4
- 
- Kotlin version: 1.9.24

**To Reproduce**
1. get bytes of heic image on device
2. try to invoke `Image.makeFromEncoded` method
3. get a crash `IllegalArgumentException: Failed to Image::makeFromEncoded`.

A simple workaround is to transform bytes with system methods:
```
@OptIn(ExperimentalForeignApi::class)
private fun ByteArray.toJpegBytes(): ByteArray = memScoped {
    val image = UIImage(data = this@toJpegBytes.toNSData())

    return UIImageJPEGRepresentation(image, compressionQuality = 0.7)!!.toByteArray()
}
```

**Comment by kirill-grouchnikov** [comment]
https://api.skia.org/classSkImage.html#:~:text=Encoded%20streams%20supported%20include%20BMP,%2C%20PNG%2C%20WBMP%2C%20WebP.

**Comment by kirill-grouchnikov** [comment]
Skiko is a wrapper around Skia, so for image format support you’d file a bug on Skia

**Comment by antailyaqwer** [comment]
> Skiko is a wrapper around Skia, so for image format support you’d file a bug on Skia

Great, thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-942">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
