### ISSUE TITLE
Skiko can't draw bold Japanese characters on macOS

### ISSUE THREAD

**Issue by RadiationX** [JetBrains/skiko#944]
If there are both Japanese and Latin characters in the same text, and the text has a bold style, then the Japanese characters are not rendered in bold.

In my case, I am making a compose multiplatform application for a Japanese dictionary and different styles are used for the text there.
At the same time, the text is rendered as it should on Android, iOS and Swing, so I decided that the problem is in Skiko|Skia.

I made a demo project to reproduce this bug (Compose + Skiko + Swing), I also tried the Native macOS example from this repository and there is the same problem.
Everything is clearly visible on the screenshot. I have also attached the archive with the demo project.

I don't know at what point it stopped working, but it definitely worked on 10/01/2023 (kotlin 1.8.20, compose 1.4.1).

The environments I was able to reproduce this bug on:
java: Zulu 17
kotlin: 1.8.20, 2.0.0
compose: 1.4.1, 1.6.10
macos: ventura(13), sonoma(14.1, 14.4.1, 14.5)
android studio: jellyfish, koala

[Demo.zip](https://github.com/user-attachments/files/15892362/Demo.zip)
<img width="813" alt="image" src="https://github.com/JetBrains/skiko/assets/5782280/c38bad89-5268-4b4d-8cfe-3dfa3d5c104b">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-944">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
