### ISSUE TITLE
Set `uniform` value for an array

### ISSUE THREAD

**Issue by mikepenz** [JetBrains/skiko#947]
For a shader with an array of colors, I am trying to understand how I can use the `skiko` `RuntimeShaderBuilder` to set a uniform of a array of `vec3`.

```glsl
const int COLOR_SIZE = 4;
uniform vec3 uColor[COLOR_SIZE];
```

Looking through all documentations of the `RuntimeShaderBuilder`, I couldn't identify the correct syntax on providing the values. 

The API overall is very similar on Android with the `RuntimeShader`. On Android it can be achieved by providing the full `FloatArray` as uniform

```
compositeRuntimeEffect.setFloatUniform("uColor", floatArrayOf(
            1f, 0f, 0f,
            0f, 1f, 1f,
            0f, 0f, 0f,
            0f, 1f, 0f
))
```

Is this currently unsupported in `skiko`, or am I overlooking a different API which needs to be used for such usecases?

Thank you.

**Comment by kirill-grouchnikov** [comment]
Looks like it's missing right now. It would need:

* New `uniform(String, FloatArray)` method in `RuntimeShaderBuilder.kt`
* Matching binding in `RuntimeShaderBuilder.cc` (both of them) to use `SkRuntimeEffectBuilder::BuilderUniform.set()` from https://api.skia.org/structSkRuntimeEffectBuilder_1_1BuilderUniform.html#ab578ef54ca285799a704884eaee37086

**Comment by kirill-grouchnikov** [comment]
But I don't think you'd get automatic conversion from an array of floats to an array of `vec3`, unless that is handled by Skia transparently in SkSL

**Comment by mikepenz** [comment]
> But I don't think you'd get automatic conversion from an array of floats to an array of `vec3`, unless that is handled by Skia transparently in SkSL

That part I don't know unfortunately. Using the similar API in Android did handle it, but that might be special to how Android does things.

**Comment by sphrak** [comment]
@kirill-grouchnikov for what its worth I made an attempt here https://github.com/sphrak/skiko/commit/ea43d0532f048fcbb0e026a6516a67ee1b35bc27 but it errors out when I try to use it in a wasmJs target w/ compose 1.7.0-alpha02 + skiko version w/ these changes. 

```
ERROR
import object field 'org_jetbrains_skia_RuntimeShaderBuilder__1nUniformFloatArray' is not a Function
```

**Comment by sphrak** [comment]
Ok managed to use this patch in a local compose-multiplatform build and it seems to work.

Regarding this:
> But I don't think you'd get automatic conversion from an array of floats to an array of vec3, unless that is handled by Skia transparently in SkSL

It seems to be handled transparently. I have tested passing a `FloatArray` and simply vary the type to `vec2[]` and `vec3[]` in shader code and it works out.

Tested this on `jvm`, `macosArm64` and `wasmJs` targets.

**vec3[] example**:

```kotlin
val demo1 = """
    uniform float width;
    uniform vec3 colors[3];   
    half4 main(vec2 coord) {
        float t = coord.x / width;
        vec3 color;
        if (t < 0.5) {
            color = mix(colors[0], colors[1], t * 2.0);
        } else {
            color = mix(colors[1], colors[2], (t - 0.5) * 2.0);
        }
        return half4(color, 1.0);
    }
""".trimIndent()

@Composable
fun Demo1(shaderRaw: String = demo1) {

    val shaderBuilder = RuntimeShaderBuilder(RuntimeEffect.makeForShader(shaderRaw))
    val colors = floatArrayOf(
        1.0f, 0.0f, 0.0f, // red
        0.0f, 1.0f, 0.0f, // green
        0.0f, 0.0f, 1.0f  // blue
    )
    shaderBuilder.uniform("colors", colors)

    Canvas(modifier = Modifier.fillMaxSize()) {
        shaderBuilder.uniform("width", size.width)
        drawIntoCanvas { canvas ->
            canvas.nativeCanvas.drawRect(
                Rect(0f, 0f, size.width, size.height),
                Paint().apply {
                    this.shader = shaderBuilder.makeShader()
                }
            )
        }
    }
}
```

<img width="1634" alt="Screenshot 2024-08-12 at 12 18 34" src="https://github.com/user-attachments/assets/82ac498c-1ad0-4f72-a33e-04299af14e29">

**Comment by mikepenz** [comment]
Thanks @sphrak for adding the functionality with your PR, and thanks @kirill-grouchnikov for looking into this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-947">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
