### ISSUE TITLE
When will the Android artifacts be published on Maven Central?

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#948]
The Android sample instructs us to set a flag and build a Android library locally.
Does that mean it's not production ready?

If I look here, I don't see an Android artifact published:
https://repo.maven.apache.org/maven2/org/jetbrains/skiko/

Is that planned? When will it happen?

**Comment by zaleslaw** [comment]
Plus one, the Android part is very important for teams lets-plot and Kotlin for Data Analysis with its library for plotting [Kandy](https://github.com/Kotlin/kandy) (we are planned to make a [next step forward](https://github.com/Kotlin/kandy/issues/289), based on Skiko, to extend data analysis capabilities for Android users)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-948">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
