### ISSUE TITLE
Feature Request: Add ability to clear CanvasRenderer to Transparent rather than White

### ISSUE THREAD

**Issue by spyderrsh** [JetBrains/skiko#949]
### Description
Have the `CanvasRenderer` be able to clear to `Color.Transparent` rather than `Color.WHITE` or possibly be able to set the clear color in `needRedraw`. The current setup prevents using canvas as an overlay over other HTML objects.

### Use Case

I'm using Kotlin Compose with WASM for web targets, and I have a use case where I need to use the `<canvas>` as an overlay for an underlying `<video>`, as WASM doesn't support video decoding very well atm. Currently, there is no method out-of-the-box to make the Compose app have no background and show the video.

### Current workaround
To clear the background, I'm calling a JS function like:
```
fun clearCanvasBackground(): Unit = js(
    """{
            var gl = document.getElementById("ComposeTarget").getContext('webgl2');
            if(gl) {
                gl.clearColor(0, 0, 0, 0);
                gl.clear(gl.COLOR_BUFFER_BIT);
            }
        }"""
)
```
The main issue is that this call is a race-condition with the Compose renderer, so I end up calling it twice like:
```
CanvasBasedWindow(title = "title", applyDefaultStyles = true) {
        var invalidations by remember { mutableStateOf(0) }
        window.onresize = {
            invalidations = 0
        }
        AppComposable()
        
        LaunchedEffect(invalidations) {
            clearCanvasBackground()
            if (invalidations < 1) {
                invalidations++
            }
        }
}
```
Secondly, if I resize the app window, the clear becomes undone, and I have to clear the window again, which risks clearing the Composable content (which may disappear). Also, after re-sizing, some circumstances with re-compositions will lead the screen to be cleared `WHITE` again.

### Project
This is by no means a min-reproduction, but you can see the results when running my project on the `refactor-compose-wasm` [branch](https://github.com/spyderrsh/xShow/tree/refactor-compose-wasm). My attempts to handle this are in `Main.wasm.kt`.

**Comment by shBLOCK** [comment]
I'm facing the same problem.
Maybe it makes sense to always clear to transparent? Drawing the background should be handled by the upper-level GUI library (eg. compose) instead of Skiko. Drawing a white background on an empty canvas is much easier than trying to make a white canvas transparent, and I don't think doing a fill would be much of a performance concern (I've heard something about "fill rate" though, so I might be wrong about this).

**Comment by shBLOCK** [comment]
Here's a less hacky temporary solution:
```kotlin
Box (modifier = Modifier.drawBehind {
    drawRect(
        color = Color.Transparent,
        size = this.size,
        blendMode = BlendMode.Clear
    )
}.fillMaxSize()) {
    <YOUR_GUI_CONTENT>
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-949">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Skaldebane** [comment]
@shBLOCK What an _elegant solution!_ Thanks a lot, had a similar use-case and that saved my butt.
