### ISSUE TITLE
JS: implement Dark theme detection

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/skiko#955]
<img width="374" alt="image" src="https://github.com/JetBrains/skiko/assets/36570577/f1ed4e92-6dcb-4ca9-82ab-3d384c281abb">

`window.matchMedia('prefers-color-scheme: dark')`

Sample [Snippet](https://github.com/JetBrains/compose-multiplatform/blob/d93351911034b723706000a8aaec203c13501783/components/resources/library/src/jsMain/kotlin/org/jetbrains/compose/resources/ResourceEnvironment.js.kt#L12C1-L23C2) is taken from compose multiplatform

```
internal actual fun getSystemEnvironment(): ResourceEnvironment {
    val locale = Intl.Locale(window.navigator.language)
    val isDarkTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
    //96 - standard browser DPI https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
    val dpi: Int = (window.devicePixelRatio * 96).toInt()
    return ResourceEnvironment(
        language = LanguageQualifier(locale.language),
        region = RegionQualifier(locale.region),
        theme = ThemeQualifier.selectByValue(isDarkTheme),
        density = DensityQualifier.selectByValue(dpi)
    )
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-955">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
