### ISSUE TITLE
WasmJs target: measureTextWidth() is returning different values on each call for the same input

### ISSUE THREAD

**Issue by kubapet** [JetBrains/skiko#962]
Putting

`val textSize = Font().measureTextWidth("some random text")
println(textSize)`

even e.g. to the main rendering loop of the example wasm application, results in arbitrary return value oscillations.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-962">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
