### ISSUE TITLE
WasmJs target: ParagraphBuilder.addText() pointer issue with empty string

### ISSUE THREAD

**Issue by kubapet** [JetBrains/skiko#963]
`val renderInfo = ParagraphBuilder(style, fontCollection)
                    .pushStyle(TextStyle().setColor(0xFF000000.toInt()).setFontSize(16f))
                    .addText("")
                    .popStyle()
                    .build()
                renderInfo.layout(Float.POSITIVE_INFINITY)
                renderInfo.paint(canvas, 5f, 5f)`

Sometimes renders random bytes from the memory (e.g. parts of strings used elsewhere in the app).
Using any non-empty string works fine.

**Comment by eymar** [comment]
It's likely related to https://github.com/JetBrains/skiko/issues/967

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-963">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
