### ISSUE TITLE
 `RuntimeException "Can't wrap nullptr"` while working with ManagedString

### ISSUE THREAD

**Issue by Schahen** [JetBrains/skiko#967]
Following code: 
```
import org.jetbrains.skia.ManagedString
import org.jetbrains.skia.shaper.IcuBidiRunIterator


val text = ""
println(ManagedString(text))
println(IcuBidiRunIterator(text, 0))
```

Fails on wasm with `RuntimeException "Can't wrap nullptr"`

**Comment by Schahen** [comment]
Here's [first commit](https://github.com/JetBrains/skiko/commit/f21b1970769b84b0c19e6306ab277b06e8703ffe) failing for test

```
 @Test
    fun bugReport() {
        ManagedString("").use { str ->
            IcuBidiRunIterator(str, false, 0)
        }
    }
```

**Comment by serjsysoev** [comment]
Confirming that this was fixed by #972, thank you!

**Comment by serjsysoev** [comment]
Can confirm, this issue is fixed. `IcuBidiRunIterator` still throws sometimes on empty input. I will file a new issue once I find a stable reproducer.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-967">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
