### ISSUE TITLE
SkiaAwtSample doesn't compile with the latest Skiko version

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/skiko#975]
skiko version: `0.8.10.1`
> e: file://.../Projects/skiko/samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/ClocksAwt.kt:15:37 Unresolved reference: makeFromFile

**Comment by MatkovIvan** [comment]
@eymar Could you please update samples after #969?

**Comment by eymar** [comment]
will do

**Comment by eymar** [comment]
Just checked. Fixed already. The changes in the examples were included in #969 which was merged today earlier.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-975">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
