### ISSUE TITLE
ManagedString constructed from empty text is not empty in wasm

### ISSUE THREAD

**Issue by serjsysoev** [JetBrains/skiko#979]
```
import org.jetbrains.skia.ManagedString


val text = ""
println("managed string `${ManagedString(text)}`")
println("managed string `${ManagedString(text)}`")
```
on wasm prints:
\`\`
\`$ \`
on on jvm prints:
\`\`
\`\`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-979">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
