### ISSUE TITLE
MSVC 32bit target support

### ISSUE THREAD

**Issue by neil4dong** [JetBrains/skiko#980]
Since compose multiplatform back to support JVM target for more compatibility.  
32bit target of kotlin native is a heavy burden to maintain (because of the LLVM kotlin compiler ...stuff things)
just I am naive, I am wondering JVM target is much easier than kotlin native.
is it possible to make a skiko(skia) prebuild target of MSVC 32bit?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-980">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
