### ISSUE TITLE
Skiko shader behavior changed between Compose 1.5.12 and 1.6.11

### ISSUE THREAD

**Issue by Martmists-GH** [JetBrains/skiko#984]
Before: ![before.webm](https://kotlinlang.slack.com/files/UBQ545HHC/F07JZGTJA30/screenshare_-_2024-08-29_11_35_13_pm.webm)

After: ![after.webm](https://kotlinlang.slack.com/files/UBQ545HHC/F07JRJTG3T9/screenshare_-_2024-08-29_11_32_51_pm.webm)

Link to discussion and reproducer on kotlinlang slack: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1724944453146279

**Comment by MatkovIvan** [comment]
Skiko does just kotlin-to-cpp bindings for a skia library and passes shaders as-is to C++/skia. It doesn't look like a binding issue, so please file the issue to Google's skia directly.

Mentioned versions match:
- Compose Multiplatform 1.5.12 -> skiko 0.7.85.4 -> skia m110
- Compose Multiplatform 1.6.11 -> skiko 0.8.4 -> skia m116

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-984">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
